"use client";

import { useEffect, useMemo, useState, useCallback } from "react";
import { monthKey, parseMonthKey } from "../../lib/date";
import { buildItemsTaskMetaMap, isAutoGeneratedTitle } from "../../lib/utils";
import type { CalendarRecord, ContentItem, ContentType } from "../../lib/types";
import { useStudioShare } from "./useStudioShare";
import { useStudioItems } from "./useStudioItems";

export interface UseStudioProps {
  calendarId: string;
  onMonthChange?: (month: Date, calId: string) => void;
  initialPresenting?: boolean;
  initialViewMode?: "calendar" | "extras" | "kanban" | "list";
  onViewModeChange?: (mode: "calendar" | "extras" | "kanban" | "list") => void;
}

export function useStudio({
  calendarId,
  onMonthChange,
  initialPresenting = false,
  initialViewMode = "calendar",
  onViewModeChange,
}: UseStudioProps) {
  const [calendar, setCalendar] = useState<CalendarRecord | null>(null);
  const [items, setItems] = useState<ContentItem[]>([]);
  const [postingDays, setPostingDays] = useState<number[]>([]);
  const [weekdayFormats, setWeekdayFormats] = useState<Record<number, ContentType>>({});
  const [customProfiles, setCustomProfiles] = useState<string[]>([]);
  const [month, setMonth] = useState(() => new Date());
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [viewMode, setViewModeState] = useState<"calendar" | "extras" | "kanban" | "list">(
    initialViewMode || "calendar"
  );

  useEffect(() => {
    if (initialViewMode && initialViewMode !== viewMode) {
      setViewModeState(initialViewMode);
    }
  }, [initialViewMode]);

  const setViewMode = useCallback(
    (mode: "calendar" | "extras" | "kanban" | "list") => {
      setViewModeState(mode);
      onViewModeChange?.(mode);
    },
    [onViewModeChange]
  );
  const [presenting, setPresenting] = useState(initialPresenting);
  const [loading, setLoading] = useState(true);
  const [notifications, setNotifications] = useState<Array<{ id: string; message: string; timestamp: Date }>>([]);

  const addNotification = useCallback((message: string) => {
    setNotifications((prev) => [
      { id: crypto.randomUUID(), message, timestamp: new Date() },
      ...prev,
    ]);
  }, []);

  const removeNotification = useCallback((id: string) => {
    setNotifications((prev) => prev.filter((n) => n.id !== id));
  }, []);

  const clearNotifications = useCallback(() => {
    setNotifications([]);
  }, []);

  const {
    showShareModal,
    setShowShareModal,
    shareUrl,
    copiedShareLink,
    loadingShareToken,
    handleOpenShareModal,
    handleCopyShareLink,
    handleGenerateNewToken,
    handleTogglePreCalendar,
  } = useStudioShare({
    calendar,
    setCalendar,
    addNotification,
  });

  const {
    availableProfiles,
    saveChanges,
    saveStatus,
    updateItem,
    handleUpdatePostingDays,
    handleUpdateWeekdayFormat,
    handleCreateProfile,
    handleDeleteProfile,
    createOn,
    createFromReference,
    createBatchItems,
    createExtra,
    removeItem,
    handleMovePost,
    handleMoveDayPosts,
    handleReorderPosts,
    handleClearMonth,
  } = useStudioItems({
    calendar,
    setCalendar,
    items,
    setItems,
    postingDays,
    setPostingDays,
    weekdayFormats,
    setWeekdayFormats,
    customProfiles,
    setCustomProfiles,
    month,
    selectedId,
    setSelectedId,
    addNotification,
  });

  const loadCalendar = useCallback(async () => {
    try {
      setLoading(true);
      const calRes = await fetch(`/api/calendars/${calendarId}`);
      const cData = await calRes.json();

      if (cData.calendar) {
        setCalendar(cData.calendar);
        if (cData.calendar.month) {
          const mDate = parseMonthKey(cData.calendar.month);
          setMonth(mDate);
          try {
            localStorage.setItem("cp:active-month", cData.calendar.month);
          } catch {}
        }
        if (Array.isArray(cData.calendar.posting_days)) {
          setPostingDays(cData.calendar.posting_days);
        }
        if (cData.calendar.weekday_formats && typeof cData.calendar.weekday_formats === "object") {
          setWeekdayFormats(cData.calendar.weekday_formats);
        }

        const serverProfiles = Array.isArray(cData.calendar.available_profiles)
          ? cData.calendar.available_profiles
          : [];
        let localProfiles: string[] = [];
        if (cData.calendar.client_id) {
          try {
            const raw = localStorage.getItem(`cp:profiles:${cData.calendar.client_id}`);
            if (raw) {
              const parsed = JSON.parse(raw);
              if (Array.isArray(parsed)) localProfiles = parsed;
            }
          } catch {}
        }
        const mergedProfiles = Array.from(new Set([...serverProfiles, ...localProfiles])).filter(Boolean);
        if (mergedProfiles.length > 0) {
          setCustomProfiles(mergedProfiles);
        }
      }
      if (Array.isArray(cData.items)) {
        setItems(cData.items);
      }
    } catch (err) {
      console.error("Error loading calendar:", err);
    } finally {
      setLoading(false);
    }
  }, [calendarId, selectedId]);

  useEffect(() => {
    loadCalendar();
  }, [loadCalendar]);

  const currentMonthKey = monthKey(month);
  const monthItems = useMemo(
    () =>
      items
        .filter((item) => item.date.startsWith(currentMonthKey))
        .sort((a, b) => {
          const dateDiff = a.date.localeCompare(b.date);
          if (dateDiff !== 0) return dateDiff;
          return (a.orderIndex ?? 0) - (b.orderIndex ?? 0);
        }),
    [items, currentMonthKey]
  );

  const selected = items.find((item) => item.id === selectedId) || null;

  const handleMonthChange = async (targetMonth: Date) => {
    if (!calendar) return;
    await saveChanges(items, calendar, postingDays, weekdayFormats, customProfiles);

    const mKey = monthKey(targetMonth);
    try {
      localStorage.setItem("cp:active-month", mKey);
    } catch {}

    setLoading(true);
    try {
      const ensureRes = await fetch("/api/calendars/ensure", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          clientId: calendar.client_id,
          month: mKey,
        }),
      });
      const ensureData = await ensureRes.json();
      const targetCalId = ensureData.calendar?.id;

      if (targetCalId) {
        onMonthChange?.(targetMonth, targetCalId);
        const calRes = await fetch(`/api/calendars/${targetCalId}`);
        const calData = await calRes.json();
        if (calData.calendar) {
          setCalendar(calData.calendar);
          setMonth(targetMonth);
          const pDays = Array.isArray(calData.calendar.posting_days)
            ? calData.calendar.posting_days
            : postingDays;
          setPostingDays(pDays);

          const incomingProfiles = Array.isArray(calData.calendar.available_profiles)
            ? calData.calendar.available_profiles
            : [];
          setCustomProfiles((prev) => {
            const merged = Array.from(new Set([...prev, ...incomingProfiles])).filter(Boolean);
            if (calData.calendar.client_id) {
              try {
                localStorage.setItem(`cp:profiles:${calData.calendar.client_id}`, JSON.stringify(merged));
              } catch {}
            }
            return merged;
          });
        }
        if (Array.isArray(calData.items)) {
          const metaMap = buildItemsTaskMetaMap(calData.items);
          const normalized = calData.items.map((entry: ContentItem) => {
            if (isAutoGeneratedTitle(entry.title, entry.profile)) {
              const meta = metaMap.get(entry.id);
              if (meta) {
                return { ...entry, title: meta.autoTitle };
              }
            }
            return entry;
          });
          setItems(normalized);
          setSelectedId(normalized.length > 0 ? normalized[0].id : null);
        }
      }
    } catch (err) {
      console.error("Error switching month:", err);
    } finally {
      setLoading(false);
    }
  };

  const handleUnapproveCalendar = useCallback(async () => {
    if (!calendar) return;
    const isPre = Boolean(
      Number(calendar.is_pre_calendar) === 1 ||
      calendar.is_pre_calendar === true
    );
    const label = isPre ? "pré-calendário" : "calendário";
    if (
      !confirm(
        `Tem certeza que deseja desaprovar este ${label}? O status de aprovação será revogado e o cliente poderá avaliá-lo novamente.`
      )
    ) {
      return;
    }

    try {
      const res = await fetch(`/api/calendars/${calendar.id}/unapprove`, {
        method: "POST",
      });
      const data = await res.json();
      if (!res.ok) {
        alert(data.error || "Não foi possível desaprovar o calendário.");
        return;
      }

      setCalendar((prev) =>
        prev
          ? {
              ...prev,
              client_feedback_status: "",
              clientFeedbackStatus: "",
              client_feedback: "",
              clientFeedback: "",
              client_feedback_at: "",
              clientFeedbackAt: "",
              status: "in_production",
            }
          : null
      );

      if (Array.isArray(data.items)) {
        setItems(data.items);
      }

      addNotification(`${isPre ? "Pré-calendário" : "Calendário"} desaprovado com sucesso!`);
    } catch (err) {
      console.error("Erro ao desaprovar calendário:", err);
      alert("Erro de conexão ao desaprovar calendário.");
    }
  }, [calendar, addNotification]);

  return {
    calendar,
    items,
    month,
    selectedId,
    setSelectedId,
    viewMode,
    setViewMode,
    presenting,
    setPresenting,
    loading,
    notifications,
    postingDays,
    weekdayFormats,
    monthItems,
    selected,
    availableProfiles,
    showShareModal,
    setShowShareModal,
    shareUrl,
    copiedShareLink,
    loadingShareToken,
    addNotification,
    removeNotification,
    clearNotifications,
    handleOpenShareModal,
    handleCopyShareLink,
    handleGenerateNewToken,
    handleTogglePreCalendar,
    handleMonthChange,
    handleUpdatePostingDays,
    handleUpdateWeekdayFormat,
    saveStatus,
    updateItem,
    handleCreateProfile,
    handleDeleteProfile,
    createOn,
    createFromReference,
    createBatchItems,
    createExtra,
    removeItem,
    handleMovePost,
    handleMoveDayPosts,
    handleReorderPosts,
    handleClearMonth,
    handleUnapproveCalendar,
  };
}
