import test from "node:test";
import assert from "node:assert/strict";
import { buildPresentationViewModel, normalizeDate, presentationFormat, presentationMetrics, stablePresentationPayload, validMonth } from "../lib/presentation-model.ts";

const base={tokenData:{month:"2026-08"},client:{id:"aline",name:"Aline Carvalho",segment:"Saúde",contentColumns:'["Educação","Marca"]'},owners:[],posts:[]};
test("valida competência e datas",()=>{assert.equal(validMonth("2026-08"),true);assert.equal(validMonth("2026-13"),false);assert.equal(normalizeDate("2026-08-12T03:00:00Z"),"2026-08-12");assert.equal(normalizeDate("12/08/2026"),null)});
test("normaliza todos os formatos sem inventar formatos",()=>{assert.equal(presentationFormat("post"),"feed");assert.equal(presentationFormat("promoted"),"feed");assert.equal(presentationFormat("linkedin"),"feed");assert.equal(presentationFormat("story"),"story");assert.equal(presentationFormat("carousel"),"carousel");assert.equal(presentationFormat("reel"),"reel")});
test("preserva e ordena vários posts na mesma data",()=>{const model=buildPresentationViewModel({...base,posts:[{id:"10",date:"2026-08-12",type:"post",head:"B",feedImages:[]},{id:"2",date:"2026-08-12",type:"carousel",head:"A",feedImages:["/a.jpg","/b.jpg"]}]});assert.deepEqual(model.posts.map(post=>post.id),["2","10"]);assert.deepEqual(model.posts[0].midias.map(item=>item.ordem),[1,2])});
test("não cria conteúdo estratégico ausente",()=>{const model=buildPresentationViewModel({...base,client:{id:"x",name:"Cliente"}});assert.deepEqual(model.estrategia,{segmento:null,tomDeVoz:null,publicoAlvo:null,colunasDeConteudo:[],observacoes:null});assert.equal(model.posts.length,0)});
test("rejeita URL executável e mantém URL HTTP ou relativa",()=>{const model=buildPresentationViewModel({...base,client:{...base.client,logoUrl:"javascript:alert(1)"},posts:[{id:"1",date:"2026-08-01",type:"post",feedImages:["javascript:alert(1)","/uploads/a.png","https://cloud.example/a.png"]}]});assert.equal(model.cliente.logoUrl,null);assert.deepEqual(model.posts[0].midias.map(item=>item.url),["/uploads/a.png","https://cloud.example/a.png"])});
test("hash lógico independe do instante de montagem",()=>{const first=buildPresentationViewModel(base);const second=buildPresentationViewModel(base);first.generatedAt="2026-01-01T00:00:00.000Z";second.generatedAt="2027-01-01T00:00:00.000Z";assert.deepEqual(stablePresentationPayload(first),stablePresentationPayload(second))});
test("recusa cliente, competência e posts inválidos",()=>{assert.throws(()=>buildPresentationViewModel({...base,tokenData:{month:"inválido"}}),/PRESENTATION_DATA_INVALID/);const model=buildPresentationViewModel({...base,posts:[{id:"",date:"2026-08-01",type:"post"},{id:"2",date:"2026-09-01",type:"post"}]});assert.equal(model.posts.length,0);assert.equal(model.avisos.length,2)});
test("calcula formatos e funil sem dividir por zero",()=>{const empty=presentationMetrics(buildPresentationViewModel(base));assert.equal(empty.total,0);assert.deepEqual(empty.formatPercent,{feed:0,story:0,carousel:0,reel:0});const model=buildPresentationViewModel({...base,posts:[{id:"1",date:"2026-08-01",type:"post",funnelStage:"topo"},{id:"2",date:"2026-08-02",type:"carousel",funnelStage:"fundo"},{id:"3",date:"2026-08-03",type:"story"},{id:"4",date:"2026-08-04",type:"reel"}]});const metrics=presentationMetrics(model);assert.deepEqual(metrics.formatPercent,{feed:25,story:25,carousel:25,reel:25});assert.deepEqual(metrics.funnelPercent,{topo:50,meio:0,fundo:50})});
