"use client";
/** Formulário que edita conteúdo, distribuição, mídia e notas internas de uma publicação. */


import { useRef, useState, useMemo } from "react";
import { Trash2, Upload, CheckCircle, FileImage, Link as LinkIcon, Smartphone, Layers, Plus, X, MessageSquare } from "lucide-react";
import { getItemTaskMeta, isAutoGeneratedTitle } from "../lib/utils";
import type { ContentItem, ContentStatus, ContentType } from "../lib/types";

/** Edita uma cópia controlada do item e devolve toda alteração ao estado do Studio. */
export function Editor({
  item,
  onChange,
  onDelete,
  availableProfiles = [],
  onCreateProfile,
  brand = "",
  allItems = [],
}: {
  item: ContentItem;
  onChange: (item: ContentItem) => void;
  onDelete: (id: string) => void;
  availableProfiles?: string[];
  onCreateProfile?: (profile: string) => void;
  brand?: string;
  allItems?: ContentItem[];
}) {
  const [tab, setTab] = useState<"content" | "media" | "notes">("content");
  const [uploadingTarget, setUploadingTarget] = useState<"feed" | "story" | null>(null);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [optimisticFeed, setOptimisticFeed] = useState<string | null>(null);
  const [optimisticStory, setOptimisticStory] = useState<string | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [showUrlInput, setShowUrlInput] = useState(false);
  const [customUrl, setCustomUrl] = useState("");
  const [showAddProfile, setShowAddProfile] = useState(false);
  const [newProfileText, setNewProfileText] = useState("");
  const fileInputRef = useRef<HTMLInputElement>(null);
  const storyFileInputRef = useRef<HTMLInputElement>(null);
  const itemRef = useRef(item);
  itemRef.current = item;

  /** Atualiza um único campo sem descartar os demais valores e entrega a cópia a `onChange`. */
  const field = (key: keyof ContentItem, value: any) =>
    onChange({ ...itemRef.current, [key]: value });

  // Reúne perfis cadastrados sem forçar arroba padrão da marca
  const profileSuggestions = useMemo(() => {
    const set = new Set<string>();
    availableProfiles.forEach((p) => {
      if (p && p.trim()) set.add(p.trim());
    });
    if (item.profile && item.profile.trim()) set.add(item.profile.trim());
    if (item.collabProfile && item.collabProfile.trim()) set.add(item.collabProfile.trim());
    return Array.from(set);
  }, [availableProfiles, item.profile, item.collabProfile]);

  // Helper para verificar se o título atual é gerado automaticamente
  const isAutoTitle = (t?: string, currentProfile?: string) => {
    if (!t) return true;
    const trimmed = t.trim();
    if (trimmed === "Nova publicação" || trimmed === "Publicação") return true;
    if (currentProfile) {
      if (trimmed === currentProfile || trimmed === `${currentProfile} (Collab)`) return true;
      if (trimmed.startsWith(`${currentProfile} + `)) return true;
    }
    return false;
  };

  const getComputedTitle = (profile?: string, isCollab?: boolean, collabProfile?: string) => {
    if (!profile) return "Nova publicação";
    if (isCollab) {
      return collabProfile ? `${profile} + ${collabProfile}` : `${profile} (Collab)`;
    }
    return profile;
  };

  const handleSelectProfile = (newProfile: string) => {
    const shouldUpdateTitle = isAutoGeneratedTitle(item.title, item.profile);
    const updatedDraft: ContentItem = {
      ...itemRef.current,
      profile: newProfile,
    };
    let newTitle = item.title;
    if (shouldUpdateTitle) {
      const itemsContext = allItems.length > 0
        ? allItems.map((it) => (it.id === item.id ? updatedDraft : it))
        : [updatedDraft];
      const meta = getItemTaskMeta(updatedDraft, itemsContext);
      newTitle = meta.autoTitle;
    }

    onChange({
      ...updatedDraft,
      title: newTitle,
    });
  };

  const handleToggleCollab = (checked: boolean) => {
    const shouldUpdateTitle = isAutoGeneratedTitle(item.title, item.profile);
    const newCollabProfile = checked ? (item.collabProfile || "") : "";
    const updatedDraft: ContentItem = {
      ...itemRef.current,
      isCollab: checked,
      collabProfile: newCollabProfile,
    };
    let newTitle = item.title;
    if (shouldUpdateTitle) {
      const itemsContext = allItems.length > 0
        ? allItems.map((it) => (it.id === item.id ? updatedDraft : it))
        : [updatedDraft];
      const meta = getItemTaskMeta(updatedDraft, itemsContext);
      newTitle = meta.autoTitle;
    }

    onChange({
      ...updatedDraft,
      title: newTitle,
    });
  };

  const handleCollabProfileChange = (collabProfile: string) => {
    const shouldUpdateTitle = isAutoGeneratedTitle(item.title, item.profile);
    const updatedDraft: ContentItem = {
      ...itemRef.current,
      collabProfile,
    };
    let newTitle = item.title;
    if (shouldUpdateTitle) {
      const itemsContext = allItems.length > 0
        ? allItems.map((it) => (it.id === item.id ? updatedDraft : it))
        : [updatedDraft];
      const meta = getItemTaskMeta(updatedDraft, itemsContext);
      newTitle = meta.autoTitle;
    }

    onChange({
      ...updatedDraft,
      collabProfile,
      title: newTitle,
    });
  };

  const handleAddProfile = () => {
    const raw = newProfileText.trim().replace(/^@+/, "");
    if (!raw) return;
    const formatted = `@${raw}`;
    if (onCreateProfile) {
      onCreateProfile(formatted);
    } else {
      handleSelectProfile(formatted);
    }
    setNewProfileText("");
    setShowAddProfile(false);
  };

  /** Envia a imagem como multipart, grava a URL retornada no item e expõe falhas no painel. */
  const handleFileUpload = async (file: File, target: "feed" | "story" = "feed") => {
    if (!file) return;
    const localUrl = URL.createObjectURL(file);
    if (target === "feed") setOptimisticFeed(localUrl);
    else setOptimisticStory(localUrl);
    setUploadingTarget(target);
    setUploadError(null);

    const formData = new FormData();
    formData.append("file", file);

    try {
      const res = await fetch("/api/upload", {
        method: "POST",
        body: formData,
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Erro ao realizar upload");

      if (target === "feed") {
        field("imageUrl", data.url);
        setOptimisticFeed(null);
      } else {
        field("storyUrl", data.url);
        setOptimisticStory(null);
      }
    } catch (err: any) {
      setUploadError(err.message || "Erro no upload");
      if (target === "feed") setOptimisticFeed(null);
      else setOptimisticStory(null);
    } finally {
      setUploadingTarget(null);
    }
  };

  /** Captura imagens coladas com Ctrl+V diretamente na tela do editor. */
  const handlePaste = (e: React.ClipboardEvent) => {
    const clipItems = e.clipboardData?.items;
    if (!clipItems) return;
    for (let i = 0; i < clipItems.length; i++) {
      if (clipItems[i].type.startsWith("image/")) {
        const file = clipItems[i].getAsFile();
        if (file) {
          e.preventDefault();
          handleFileUpload(file, "feed");
          break;
        }
      }
    }
  };

  /** Impede a abertura do arquivo pelo navegador e envia o primeiro item arrastado. */
  const handleDrop = (e: React.DragEvent, target: "feed" | "story" = "feed") => {
    e.preventDefault();
    if (e.dataTransfer.files?.[0]) {
      handleFileUpload(e.dataTransfer.files[0], target);
    }
  };

  const handleApplyUrl = () => {
    if (customUrl.trim()) {
      field("imageUrl", customUrl.trim());
      setCustomUrl("");
      setShowUrlInput(false);
    }
  };

  const activeFeedImage =
    optimisticFeed ||
    item.imageUrl ||
    (item as any).image_url ||
    (item as any).imageurl ||
    "";

  const activeStoryImage =
    optimisticStory ||
    item.storyUrl ||
    (item as any).story_url ||
    (item as any).storyurl ||
    "";

  const isFeedAndStory = item.type === "Feed e Story";
  const isStoryOnly = item.type === "Story";
  const currentMeta = getItemTaskMeta(item, allItems);

  return (
    <div className="editorRoot" onPaste={handlePaste}>
      {/* UI: abas separam conteúdo, arquivo publicado e anotações privadas da equipe. */}
      <div className="editorTabs">
        {/* UI: a aba ativa determina apenas o painel visível; o item permanece o mesmo. */}
        <button
          className={tab === "content" ? "active" : ""}
          onClick={() => setTab("content")}
        >
          Conteúdo
        </button>
        <button
          className={tab === "media" ? "active" : ""}
          onClick={() => setTab("media")}
        >
          Mídia {item.imageUrl && <span className="mediaActiveDot" />}
        </button>
        <button
          className={tab === "notes" ? "active" : ""}
          onClick={() => setTab("notes")}
        >
          Notas Internas
        </button>

        {/* UI: Seletor de status da produção no topo da barra e botão de exclusão. */}
        <div className="editorTabActions">
          <div className="headerStatusSelector" title="Status da Produção">
            <span className="headerStatusDot" data-status={item.status} />
            <select
              value={item.status}
              onChange={(e) => field("status", e.target.value as ContentStatus)}
              className="headerStatusSelect"
            >
              {["Ideia", "Produção", "Revisão", "Aprovado"].map((value) => (
                <option key={value} value={value}>
                  {value}
                </option>
              ))}
            </select>
          </div>

          <button
            className="deleteAction"
            onClick={() => onDelete(item.id)}
            title="Excluir esta publicação"
          >
            <Trash2 size={14} />
          </button>
        </div>
      </div>

      {tab === "content" && (
        <div className="editorScroll">
          {((item as any).clientComment || (item as any).client_comment) && (
            <div className="clientCommentBanner">
              <div className="clientCommentBannerHeader">
                <MessageSquare size={13} />
                <strong>Observação do Cliente:</strong>
              </div>
              <p className="clientCommentText">"{item.clientComment || (item as any).client_comment}"</p>
            </div>
          )}

          {/* Identificação estruturada da arte / tarefa */}
          <div className="editorTaskHeader">
            <span className={`editorTaskTag ${currentMeta.isCollab ? "collabTag" : ""}`}>
              {currentMeta.tag}
            </span>
            <span className="editorTaskProfile">
              {currentMeta.profile || "Sem perfil vinculado"}
            </span>
          </div>

          <textarea
            className="documentTitle"
            value={item.title}
            onChange={(e) => field("title", e.target.value)}
            placeholder={currentMeta.autoTitle || "Título interno da publicação..."}
            rows={1}
          />

          {/* UI: metadados operacionais usados no calendário e no fluxo de produção. */}
          <div className="metaGrid">
            <label>
              <span>Data Agendada</span>
              <input
                type="date"
                value={item.date}
                onChange={(e) => field("date", e.target.value)}
                style={{ fontWeight: 800 }}
              />
            </label>
            <label>
              <span>Formato</span>
              <select
                value={item.type || "Feed e Story"}
                onChange={(e) => field("type", e.target.value as ContentType)}
              >
                {["Feed e Story", "Feed", "Story", "Carrossel", "Reels"].map((value) => (
                  <option key={value}>{value}</option>
                ))}
              </select>
            </label>
            <label>
              <span>Canal / Rede</span>
              <input
                value={item.channel}
                onChange={(e) => field("channel", e.target.value)}
              />
            </label>
          </div>

          {/* UI: copy, objetivo, briefing, funil, CTA e hashtags que compõem o post (conteúdo principal). */}
          <div className="copyGrid">
            <label>
              <span>Head (Título principal na arte)</span>
              <input
                value={item.head || ""}
                onChange={(e) => field("head", e.target.value)}
                placeholder="Texto de destaque na arte visual..."
              />
            </label>
            <label>
              <span>Subhead (Linha de apoio na arte)</span>
              <input
                value={item.subhead || ""}
                onChange={(e) => field("subhead", e.target.value)}
                placeholder="Texto secundário da arte..."
              />
            </label>
            <label className="wide grow">
              <span>Legenda Completa (Copy)</span>
              <textarea
                value={item.caption}
                onChange={(e) => field("caption", e.target.value)}
                placeholder="Texto completo da legenda da publicação..."
              />
            </label>
            <label>
              <span>Objetivo da Publicação</span>
              <input
                value={item.objective}
                onChange={(e) => field("objective", e.target.value)}
                placeholder="Ex: Gerar engajamento, captar leads, branding..."
              />
            </label>
            <label>
              <span>Briefing Visual (Instrução para o Designer)</span>
              <textarea
                value={item.visual}
                onChange={(e) => field("visual", e.target.value)}
                placeholder="Orientação de design, referências, iluminação e elementos..."
              />
            </label>
            <label>
              <span>Etapa do Funil</span>
              <select
                value={item.funnelStage || "Topo"}
                onChange={(e) => field("funnelStage", e.target.value)}
              >
                {["Topo", "Meio", "Fundo"].map((value) => (
                  <option key={value}>{value}</option>
                ))}
              </select>
            </label>
            <label>
              <span>Chamada para Ação (CTA)</span>
              <input
                value={item.cta || ""}
                onChange={(e) => field("cta", e.target.value)}
                placeholder="Ex: Salve este post / Link na bio"
              />
            </label>
            <label className="wide">
              <span>Hashtags</span>
              <input
                value={item.hashtags || ""}
                onChange={(e) => field("hashtags", e.target.value)}
                placeholder="#design #conteudo #marketing"
              />
            </label>
          </div>

          {/* UI: define o perfil principal e, opcionalmente, o parceiro da publicação collab. */}
          <div className="profileCollabBox">
            {/* UI: o interruptor também apaga o segundo perfil ao desativar a collab. */}
            <div className="profileCollabHeader">
              <div>
                <span className="sectionTag">Distribuição de Perfis</span>
                <strong>Publicação em Perfil / Collab</strong>
              </div>
              <div className="profileCollabHeaderActions">
                {!showAddProfile && (
                  <button
                    type="button"
                    className="addProfileSmallBtn"
                    onClick={() => setShowAddProfile(true)}
                    title="Criar novo perfil (@)"
                  >
                    <Plus size={12} />
                    <span>{profileSuggestions.length === 0 ? "Criar Perfil" : "Novo Perfil"}</span>
                  </button>
                )}
                <label className="collabSwitchLabel">
                  <input
                    type="checkbox"
                    checked={Boolean(item.isCollab)}
                    onChange={(e) => handleToggleCollab(e.target.checked)}
                  />
                  <span className="collabSwitchBadge">
                    {item.isCollab ? "Collab Ativo" : "Collab Desativado"}
                  </span>
                </label>
              </div>
            </div>

            {/* Criação inline de perfil quando solicitado */}
            {showAddProfile && (
              <div className="addProfileInlineBox">
                <div className="addProfileInputGroup">
                  <span className="addProfilePrefix">@</span>
                  <input
                    type="text"
                    placeholder={profileSuggestions.length === 0 ? "nome_do_perfil (atribui a todas as artes)" : "segundo_perfil"}
                    value={newProfileText.replace(/^@/, "")}
                    onChange={(e) => setNewProfileText(e.target.value.replace(/^@/, ""))}
                    onKeyDown={(e) => {
                      if (e.key === "Enter") {
                        e.preventDefault();
                        handleAddProfile();
                      }
                    }}
                    autoFocus
                  />
                </div>
                <button
                  type="button"
                  className="confirmAddProfileBtn"
                  onClick={handleAddProfile}
                  title="Confirmar criação do perfil"
                >
                  <Plus size={13} />
                  <span>{profileSuggestions.length === 0 ? "Criar e Atribuir a Todas as Artes" : "Adicionar Perfil"}</span>
                </button>
                <button
                  type="button"
                  className="cancelAddProfileBtn"
                  onClick={() => {
                    setShowAddProfile(false);
                    setNewProfileText("");
                  }}
                >
                  Cancelar
                </button>
              </div>
            )}

            {/* UI: distribuição de perfis: colunas perfeitamente alinhadas */}
            <div className="profileFieldsGrid">
              <div className="profileField">
                <div className="profileHeaderRow">
                  <span>Perfil Principal ({item.isCollab ? "Autor 1" : "Conta"})</span>
                </div>

                <div className="profileCurrentInputGroup">
                  <input
                    id="mainProfileInput"
                    type="text"
                    value={item.profile || ""}
                    onChange={(e) => handleSelectProfile(e.target.value)}
                    placeholder={
                      profileSuggestions.length === 0
                        ? "Sem perfil vinculado (clique em Criar Perfil acima)"
                        : "Selecione um perfil abaixo ou digite @perfil"
                    }
                  />
                  {item.profile && (
                    <button
                      type="button"
                      className="clearProfileBtn"
                      onClick={() => handleSelectProfile("")}
                      title="Remover arroba desta publicação"
                    >
                      <X size={14} />
                    </button>
                  )}
                </div>

                {profileSuggestions.length > 0 && (
                  <div className="profilePills">
                    <button
                      type="button"
                      className={!item.profile ? "active outline" : ""}
                      onClick={() => handleSelectProfile("")}
                      title="Publicar sem arroba vinculado"
                    >
                      Sem @
                    </button>
                    {profileSuggestions.map((p) => (
                      <button
                        key={p}
                        type="button"
                        className={item.profile === p ? "active" : ""}
                        onClick={() => handleSelectProfile(p)}
                      >
                        {p}
                      </button>
                    ))}
                  </div>
                )}
              </div>

              {item.isCollab && (
                <div className="profileField collabField">
                  <div className="profileHeaderRow">
                    <span>Perfil Colaborador (Autor 2 / Parceiro)</span>
                  </div>
                  <div className="profileCurrentInputGroup">
                    <input
                      type="text"
                      value={item.collabProfile || ""}
                      onChange={(e) => handleCollabProfileChange(e.target.value)}
                      placeholder="Ex: @perfilB ou @parceiro"
                    />
                    {item.collabProfile && (
                      <button
                        type="button"
                        className="clearProfileBtn"
                        onClick={() => handleCollabProfileChange("")}
                        title="Remover colaborador desta publicação"
                      >
                        <X size={14} />
                      </button>
                    )}
                  </div>
                  {profileSuggestions.length > 0 && (
                    <div className="profilePills">
                      <button
                        type="button"
                        className={!item.collabProfile ? "active outline" : ""}
                        onClick={() => handleCollabProfileChange("")}
                        title="Sem colaborador"
                      >
                        Sem @
                      </button>
                      {profileSuggestions.map((p) => (
                        <button
                          key={p}
                          type="button"
                          className={item.collabProfile === p ? "active" : ""}
                          onClick={() => handleCollabProfileChange(p)}
                        >
                          {p}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>

            {item.isCollab && (
              <div className="collabNotice">
                <span className="collabDot" />
                <span>
                  Esta publicação será apresentada em conjunto como collab entre{" "}
                  <strong>{item.profile || "Perfil A"}</strong> e{" "}
                  <strong>{item.collabProfile || "Perfil B"}</strong>.
                </span>
              </div>
            )}
          </div>

          {/* UI: Botões compactos de anexo de arte (Feed e Story) — largura ajustada, não toma a tela inteira */}
          <div className="mediaButtonsSection">
            {/* Input escondido para Feed */}
            <input
              ref={fileInputRef}
              type="file"
              accept="image/*"
              hidden
              onChange={(e) => {
                if (e.target.files?.[0]) handleFileUpload(e.target.files[0], "feed");
              }}
            />
            {/* Input escondido para Story */}
            <input
              ref={storyFileInputRef}
              type="file"
              accept="image/*"
              hidden
              onChange={(e) => {
                if (e.target.files?.[0]) handleFileUpload(e.target.files[0], "story");
              }}
            />

            <div className="mediaButtonsHeader">
              <span className="sectionTag">Artes da Publicação</span>
            </div>

            <div className="mediaButtonsGroup">
              {isFeedAndStory ? (
                <>
                  {/* Botão Arte Feed */}
                  <div className="mediaCompactItem">
                    <button
                      type="button"
                      className={`mediaCompactBtn ${activeFeedImage ? "hasMedia" : ""}`}
                      onClick={() => fileInputRef.current?.click()}
                      disabled={uploadingTarget === "feed"}
                      title={activeFeedImage ? "Clique para trocar a arte do Feed" : "Clique para anexar a arte do Feed"}
                    >
                      <Layers size={14} className="mediaBtnIcon" />
                      <span className="mediaBtnLabel">
                        {uploadingTarget === "feed"
                          ? "Enviando Feed..."
                          : activeFeedImage
                          ? "Feed Anexado"
                          : "Anexar Feed"}
                      </span>
                      <span className="mediaBtnFormat">1:1 / 4:5</span>
                      {activeFeedImage ? (
                        <span className="mediaMiniBadge success" title="Arte anexada">
                          <CheckCircle size={10} /> Anexada
                        </span>
                      ) : (
                        <span className="mediaMiniBadge pending">Pendente</span>
                      )}
                    </button>
                    {activeFeedImage && (
                      <button
                        type="button"
                        className="mediaCompactRemoveBtn"
                        onClick={() => {
                          setOptimisticFeed(null);
                          field("imageUrl", "");
                        }}
                        title="Remover arte do Feed"
                      >
                        <X size={12} />
                      </button>
                    )}
                  </div>

                  {/* Botão Arte Story */}
                  <div className="mediaCompactItem">
                    <button
                      type="button"
                      className={`mediaCompactBtn ${activeStoryImage ? "hasMedia" : ""}`}
                      onClick={() => storyFileInputRef.current?.click()}
                      disabled={uploadingTarget === "story"}
                      title={activeStoryImage ? "Clique para trocar a arte do Story" : "Clique para anexar a arte do Story"}
                    >
                      <Smartphone size={14} className="mediaBtnIcon" />
                      <span className="mediaBtnLabel">
                        {uploadingTarget === "story"
                          ? "Enviando Story..."
                          : activeStoryImage
                          ? "Story Anexado"
                          : "Anexar Story"}
                      </span>
                      <span className="mediaBtnFormat">9:16</span>
                      {activeStoryImage ? (
                        <span className="mediaMiniBadge success" title="Arte anexada">
                          <CheckCircle size={10} /> Anexada
                        </span>
                      ) : (
                        <span className="mediaMiniBadge pending">Pendente</span>
                      )}
                    </button>
                    {activeStoryImage && (
                      <button
                        type="button"
                        className="mediaCompactRemoveBtn"
                        onClick={() => {
                          setOptimisticStory(null);
                          field("storyUrl", "");
                        }}
                        title="Remover arte do Story"
                      >
                        <X size={12} />
                      </button>
                    )}
                  </div>
                </>
              ) : isStoryOnly ? (
                /* Botão apenas Story */
                <div className="mediaCompactItem">
                  <button
                    type="button"
                    className={`mediaCompactBtn ${activeStoryImage || activeFeedImage ? "hasMedia" : ""}`}
                    onClick={() => storyFileInputRef.current?.click()}
                    disabled={uploadingTarget === "story"}
                    title={activeStoryImage || activeFeedImage ? "Clique para trocar a arte do Story" : "Clique para anexar a arte do Story"}
                  >
                    <Smartphone size={14} className="mediaBtnIcon" />
                    <span className="mediaBtnLabel">
                      {uploadingTarget === "story"
                        ? "Enviando Story..."
                        : (activeStoryImage || activeFeedImage)
                        ? "Story Anexado"
                        : "Anexar Story"}
                    </span>
                    <span className="mediaBtnFormat">9:16</span>
                    {activeStoryImage || activeFeedImage ? (
                      <span className="mediaMiniBadge success" title="Arte anexada">
                        <CheckCircle size={10} /> Anexada
                      </span>
                    ) : (
                      <span className="mediaMiniBadge pending">Pendente</span>
                    )}
                  </button>
                  {(activeStoryImage || activeFeedImage) && (
                    <button
                      type="button"
                      className="mediaCompactRemoveBtn"
                      onClick={() => {
                        setOptimisticStory(null);
                        setOptimisticFeed(null);
                        field("storyUrl", "");
                        field("imageUrl", "");
                      }}
                      title="Remover arte do Story"
                    >
                      <X size={12} />
                    </button>
                  )}
                </div>
              ) : (
                /* Botão Feed / Carrossel / Reels */
                <div className="mediaCompactItem">
                  <button
                    type="button"
                    className={`mediaCompactBtn ${activeFeedImage ? "hasMedia" : ""}`}
                    onClick={() => fileInputRef.current?.click()}
                    disabled={uploadingTarget === "feed"}
                    title={activeFeedImage ? "Clique para trocar a arte" : "Clique para anexar a arte"}
                  >
                    <FileImage size={14} className="mediaBtnIcon" />
                    <span className="mediaBtnLabel">
                      {uploadingTarget === "feed"
                        ? "Enviando..."
                        : activeFeedImage
                        ? "Arte Anexada"
                        : "Anexar Arte"}
                    </span>
                    {activeFeedImage ? (
                      <span className="mediaMiniBadge success" title="Arte anexada">
                        <CheckCircle size={10} /> Anexada
                      </span>
                    ) : (
                      <span className="mediaMiniBadge pending">Pendente</span>
                    )}
                  </button>
                  {activeFeedImage && (
                    <button
                      type="button"
                      className="mediaCompactRemoveBtn"
                      onClick={() => {
                        setOptimisticFeed(null);
                        field("imageUrl", "");
                      }}
                      title="Remover arte da publicação"
                    >
                      <X size={12} />
                    </button>
                  )}
                </div>
              )}
            </div>

            {uploadError && (
              <div className="uploadAlert error" style={{ marginTop: 8 }}>
                <span>{uploadError}</span>
              </div>
            )}
          </div>
        </div>
      )}

      {tab === "media" && (
        <div className="mediaPanel">
          {/* UI: introduz o armazenamento real da imagem associada a esta publicação. */}
          <div className="mediaHeader">
            {/* UI: título e instrução deixam claro que o arquivo será persistido no servidor. */}
            <div className="mediaHeaderTitle">
              <FileImage size={18} />
              <div>
                <strong>Mídia Real da Publicação</strong>
                <p>Faça o upload do arquivo real (PNG, JPG, WEBP). Ele será salvo no servidor e exibido no calendário.</p>
              </div>
            </div>
          </div>

          {/* UI: área clicável e arrastável que envia uma imagem ao servidor. */}
          <div
            className={`uploadDropzone ${uploadingTarget ? "uploading" : ""}`}
            onDragOver={(e) => e.preventDefault()}
            onDrop={handleDrop}
            onClick={() => fileInputRef.current?.click()}
          >
            <Upload size={32} className="uploadIcon" />
            <div className="dropzoneCopy">
              <strong>{uploadingTarget ? "Enviando arquivo ao servidor..." : "Clique ou arraste uma imagem aqui"}</strong>
              <span>Formatos suportados: PNG, JPG, JPEG, WEBP e GIF</span>
            </div>
            <button
              type="button"
              className="primaryButton compactBtn"
              disabled={uploadingTarget !== null}
            >
              {uploadingTarget ? "Gravando..." : "Selecionar do Computador"}
            </button>
          </div>

          {uploadError && (
            <div className="uploadAlert error">
              <span>{uploadError}</span>
            </div>
          )}

          {/* UI: mídia persistida exibida em miniaturas elegantes e compactas */}
          {activeFeedImage ? (
            <div className="uploadedMediaCard compactMediaCard">
              <div className="mediaThumbnailBox">
                <img
                  src={activeFeedImage}
                  alt={item.title}
                  className="mediaThumbnailImg"
                />
              </div>

              <div className="mediaMetaDetails">
                <div className="mediaCardTop">
                  <span className="mediaStatusLabel">
                    <CheckCircle size={14} color="#10b981" /> Arte do Feed (1:1 / 4:5 / 1080×1440)
                  </span>
                  <div style={{ display: "flex", gap: 6 }}>
                    <button
                      type="button"
                      className="secondarySmallBtn"
                      onClick={() => window.open(activeFeedImage, "_blank")}
                    >
                      Abrir
                    </button>
                    <button
                      type="button"
                      className="dangerSmallBtn"
                      onClick={() => {
                        setOptimisticFeed(null);
                        field("imageUrl", "");
                      }}
                    >
                      Remover
                    </button>
                  </div>
                </div>

                <div className="mediaUrlRow">
                  <small>URL:</small>
                  <code>{item.imageUrl || "Enviando..."}</code>
                </div>
              </div>
            </div>
          ) : (
            <div className="noMediaNotice">
              <p>Nenhuma arte de Feed associada a este card ainda. Faça o upload acima ou cole com <b>Ctrl+V</b>.</p>
            </div>
          )}

          {activeStoryImage && (
            <div className="uploadedMediaCard compactMediaCard" style={{ marginTop: 10 }}>
              <div className="mediaThumbnailBox storyThumbBox">
                <img
                  src={activeStoryImage}
                  alt={`${item.title} - Story`}
                  className="mediaThumbnailImg"
                />
              </div>

              <div className="mediaMetaDetails">
                <div className="mediaCardTop">
                  <span className="mediaStatusLabel">
                    <CheckCircle size={14} color="#10b981" /> Arte do Story (9:16)
                  </span>
                  <div style={{ display: "flex", gap: 6 }}>
                    <button
                      type="button"
                      className="secondarySmallBtn"
                      onClick={() => window.open(activeStoryImage, "_blank")}
                    >
                      Abrir
                    </button>
                    <button
                      type="button"
                      className="dangerSmallBtn"
                      onClick={() => {
                        setOptimisticStory(null);
                        field("storyUrl", "");
                      }}
                    >
                      Remover
                    </button>
                  </div>
                </div>

                <div className="mediaUrlRow">
                  <small>URL:</small>
                  <code>{item.storyUrl || "Enviando..."}</code>
                </div>
              </div>
            </div>
          )}

          <div style={{ marginTop: 12, display: "flex", flexDirection: "column", gap: 8 }}>
            {!showUrlInput ? (
              <button
                type="button"
                className="secondarySmallBtn"
                style={{ alignSelf: "flex-start" }}
                onClick={() => setShowUrlInput(true)}
              >
                <LinkIcon size={12} /> Ou colar link direto de imagem externa
              </button>
            ) : (
              <div style={{ display: "flex", gap: 6, width: "100%", maxWidth: 540 }}>
                <input
                  type="url"
                  value={customUrl}
                  onChange={(e) => setCustomUrl(e.target.value)}
                  placeholder="https://exemplo.com/imagem.png"
                  style={{ flex: 1, padding: "6px 10px", fontSize: 12, borderRadius: 6, border: "1px solid var(--border)" }}
                />
                <button
                  type="button"
                  className="primaryButton compactBtn"
                  onClick={handleApplyUrl}
                >
                  Salvar Link
                </button>
                <button
                  type="button"
                  className="secondarySmallBtn"
                  onClick={() => setShowUrlInput(false)}
                >
                  Cancelar
                </button>
              </div>
            )}
          </div>
        </div>
      )}

      {tab === "notes" && (
        <div className="notesPanel">
          {/* UI: aviso de que estas observações são internas e não aparecem na apresentação. */}
          <div className="notesHeader">
            <strong>Alinhamento Interno (Designer ⇄ Social Media)</strong>
            <p>Observações privadas da equipe sobre este card.</p>
          </div>
          <textarea
            value={item.internalNotes || ""}
            onChange={(e) => field("internalNotes", e.target.value)}
            placeholder="Digite feedbacks, links de assets no Figma, ou notas entre designer e social media..."
            rows={8}
          />
        </div>
      )}
    </div>
  );
}
