"use client";
/** Formulário que edita conteúdo, distribuição, mídia e notas internas de uma publicação. */

import { useRef, useState, useMemo } from "react";
import { Trash2 } from "lucide-react";
import { getItemTaskMeta, isAutoGeneratedTitle } from "../lib/utils";
import type { ContentItem } from "../lib/types";
import { EditorContentTab } from "./editor/EditorContentTab";
import { EditorMediaTab } from "./editor/EditorMediaTab";
import { EditorNotesTab } from "./editor/EditorNotesTab";

export function Editor({
  item,
  onChange,
  onDelete,
  availableProfiles = [],
  onCreateProfile,
  onDeleteProfile,
  allItems = [],
  allCalendarItems = [],
}: {
  item: ContentItem;
  onChange: (item: ContentItem) => void;
  onDelete: (id: string) => void;
  availableProfiles?: string[];
  onCreateProfile?: (profile: string) => void;
  onDeleteProfile?: (profile: string) => void;
  brand?: string;
  allItems?: ContentItem[];
  allCalendarItems?: ContentItem[];
}) {
  const [tab, setTab] = useState<"content" | "media" | "notes">("content");
  const [uploadingTarget, setUploadingTarget] = useState<"feed" | "story" | null>(null);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [optimisticFeed, setOptimisticFeed] = useState<string | null>(null);
  const [optimisticStory, setOptimisticStory] = useState<string | null>(null);
  const [showUrlInput, setShowUrlInput] = useState(false);
  const [customUrl, setCustomUrl] = useState("");
  const [deletedProfiles, setDeletedProfiles] = useState<string[]>([]);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const storyFileInputRef = useRef<HTMLInputElement>(null);
  const itemRef = useRef(item);
  itemRef.current = item;

  const field = (key: keyof ContentItem, value: any) =>
    onChange({ ...itemRef.current, [key]: value });

  const profileSuggestions = useMemo(() => {
    const set = new Set<string>();
    availableProfiles.forEach((p) => {
      if (p && p.trim() && !deletedProfiles.includes(p.trim())) set.add(p.trim());
    });
    if (item.profile && item.profile.trim() && !deletedProfiles.includes(item.profile.trim())) {
      set.add(item.profile.trim());
    }
    if (item.collabProfile && item.collabProfile.trim() && !deletedProfiles.includes(item.collabProfile.trim())) {
      set.add(item.collabProfile.trim());
    }
    return Array.from(set);
  }, [availableProfiles, item.profile, item.collabProfile, deletedProfiles]);

  const isProfileInUse = (p: string) => {
    if (item.profile === p) return true;
    if (item.isCollab && item.collabProfile === p) return true;
    const pool = allCalendarItems && allCalendarItems.length > 0 ? allCalendarItems : allItems;
    return pool.some((it) => {
      if (it.id === item.id) return false;
      if (it.profile === p) return true;
      if (it.isCollab && it.collabProfile === p) return true;
      return false;
    });
  };

  const handleSelectProfile = (newProfile: string) => {
    const shouldUpdateTitle = isAutoGeneratedTitle(item.title, item.profile);
    const updatedDraft: ContentItem = {
      ...itemRef.current,
      profile: newProfile,
    };
    let newTitle = item.title;
    if (shouldUpdateTitle) {
      const itemsContext = allItems.length > 0
        ? allItems.map((it) => (it.id === item.id ? updatedDraft : it))
        : [updatedDraft];
      const meta = getItemTaskMeta(updatedDraft, itemsContext);
      newTitle = meta.autoTitle;
    }

    onChange({
      ...updatedDraft,
      title: newTitle,
    });
  };

  const handleToggleCollab = (checked: boolean) => {
    const shouldUpdateTitle = isAutoGeneratedTitle(item.title, item.profile);
    const newCollabProfile = checked ? (item.collabProfile || "") : "";
    const updatedDraft: ContentItem = {
      ...itemRef.current,
      isCollab: checked,
      collabProfile: newCollabProfile,
    };
    let newTitle = item.title;
    if (shouldUpdateTitle) {
      const itemsContext = allItems.length > 0
        ? allItems.map((it) => (it.id === item.id ? updatedDraft : it))
        : [updatedDraft];
      const meta = getItemTaskMeta(updatedDraft, itemsContext);
      newTitle = meta.autoTitle;
    }

    onChange({
      ...updatedDraft,
      title: newTitle,
    });
  };

  const handleCollabProfileChange = (collabProfile: string) => {
    const shouldUpdateTitle = isAutoGeneratedTitle(item.title, item.profile);
    const updatedDraft: ContentItem = {
      ...itemRef.current,
      collabProfile,
    };
    let newTitle = item.title;
    if (shouldUpdateTitle) {
      const itemsContext = allItems.length > 0
        ? allItems.map((it) => (it.id === item.id ? updatedDraft : it))
        : [updatedDraft];
      const meta = getItemTaskMeta(updatedDraft, itemsContext);
      newTitle = meta.autoTitle;
    }

    onChange({
      ...updatedDraft,
      collabProfile,
      title: newTitle,
    });
  };

  const handleDeleteProfileClick = (e: React.MouseEvent, p: string) => {
    e.stopPropagation();
    e.preventDefault();
    setDeletedProfiles((prev) => [...prev, p]);
    if (item.profile === p) {
      handleSelectProfile("");
    }
    if (item.collabProfile === p) {
      handleCollabProfileChange("");
    }
    onDeleteProfile?.(p);
  };

  const handleFileUpload = async (file: File, target: "feed" | "story" = "feed") => {
    if (!file) return;
    const localUrl = URL.createObjectURL(file);
    if (target === "feed") setOptimisticFeed(localUrl);
    else setOptimisticStory(localUrl);
    setUploadingTarget(target);
    setUploadError(null);

    const formData = new FormData();
    formData.append("file", file);

    try {
      const res = await fetch("/api/upload", {
        method: "POST",
        body: formData,
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Erro ao realizar upload");

      if (target === "feed") {
        field("imageUrl", data.url);
        setOptimisticFeed(null);
      } else {
        field("storyUrl", data.url);
        setOptimisticStory(null);
      }
    } catch (err: any) {
      setUploadError(err.message || "Erro no upload");
      if (target === "feed") setOptimisticFeed(null);
      else setOptimisticStory(null);
    } finally {
      setUploadingTarget(null);
    }
  };

  const handlePaste = (e: React.ClipboardEvent) => {
    const clipItems = e.clipboardData?.items;
    if (!clipItems) return;
    for (let i = 0; i < clipItems.length; i++) {
      if (clipItems[i].type.startsWith("image/")) {
        const file = clipItems[i].getAsFile();
        if (file) {
          e.preventDefault();
          handleFileUpload(file, "feed");
          break;
        }
      }
    }
  };

  const handleDrop = (e: React.DragEvent, target: "feed" | "story" = "feed") => {
    e.preventDefault();
    if (e.dataTransfer.files?.[0]) {
      handleFileUpload(e.dataTransfer.files[0], target);
    }
  };

  const handleApplyUrl = () => {
    if (customUrl.trim()) {
      field("imageUrl", customUrl.trim());
      setCustomUrl("");
      setShowUrlInput(false);
    }
  };

  const activeFeedImage =
    optimisticFeed ||
    item.imageUrl ||
    (item as any).image_url ||
    (item as any).imageurl ||
    "";

  const activeStoryImage =
    optimisticStory ||
    item.storyUrl ||
    (item as any).story_url ||
    (item as any).storyurl ||
    "";

  const isFeedAndStory = item.type === "Feed e Story";
  const isStoryOnly = item.type === "Story";
  const currentMeta = getItemTaskMeta(item, allItems);

  return (
    <div className="editorRoot" onPaste={handlePaste}>
      <div className="editorTabs">
        <button
          className={tab === "content" ? "active" : ""}
          onClick={() => setTab("content")}
        >
          Conteúdo
        </button>
        <button
          className={tab === "media" ? "active" : ""}
          onClick={() => setTab("media")}
        >
          Mídia {item.imageUrl && <span className="mediaActiveDot" />}
        </button>
        <button
          className={tab === "notes" ? "active" : ""}
          onClick={() => setTab("notes")}
        >
          Notas Internas
        </button>
        <div className="editorActions">
          <button
            className="deleteAction"
            onClick={() => onDelete(item.id)}
            title="Excluir esta publicação"
          >
            <Trash2 size={14} />
          </button>
        </div>
      </div>

      {tab === "content" && (
        <EditorContentTab
          item={item}
          field={field}
          currentMeta={currentMeta}
          profileSuggestions={profileSuggestions}
          isProfileInUse={isProfileInUse}
          onSelectProfile={handleSelectProfile}
          onToggleCollab={handleToggleCollab}
          onCollabProfileChange={handleCollabProfileChange}
          onDeleteProfileClick={handleDeleteProfileClick}
          onCreateProfile={onCreateProfile}
          fileInputRef={fileInputRef}
          storyFileInputRef={storyFileInputRef}
          activeFeedImage={activeFeedImage}
          activeStoryImage={activeStoryImage}
          uploadingTarget={uploadingTarget}
          uploadError={uploadError}
          onUploadFile={handleFileUpload}
          onRemoveFeedImage={() => {
            setOptimisticFeed(null);
            field("imageUrl", "");
          }}
          onRemoveStoryImage={() => {
            setOptimisticStory(null);
            field("storyUrl", "");
          }}
          isFeedAndStory={isFeedAndStory}
          isStoryOnly={isStoryOnly}
        />
      )}

      {tab === "media" && (
        <EditorMediaTab
          activeFeedImage={activeFeedImage}
          activeStoryImage={activeStoryImage}
          uploadingTarget={uploadingTarget}
          uploadError={uploadError}
          onDrop={handleDrop}
          onSelectComputerFile={() => fileInputRef.current?.click()}
          onRemoveFeedImage={() => {
            setOptimisticFeed(null);
            field("imageUrl", "");
          }}
          onRemoveStoryImage={() => {
            setOptimisticStory(null);
            field("storyUrl", "");
          }}
          customUrl={customUrl}
          setCustomUrl={setCustomUrl}
          showUrlInput={showUrlInput}
          setShowUrlInput={setShowUrlInput}
          onApplyUrl={handleApplyUrl}
          itemTitle={item.title}
          feedUrl={item.imageUrl}
          storyUrl={item.storyUrl}
        />
      )}

      {tab === "notes" && (
        <EditorNotesTab
          notes={item.internalNotes || ""}
          onChangeNotes={(notes) => field("internalNotes", notes)}
        />
      )}
    </div>
  );
}
