import { NextRequest, NextResponse } from 'next/server';
import { getDbPool } from '../../../../../lib/db';
import { notificationSession } from '../../../../../lib/notifications';
const FINAL=['publicado','arquivado','cancelado'];
const EVENTS=['planning_sent_to_design','artwork_awaiting_approval','planning_sent_to_approval','artwork_approve','post_scheduled','post_published'];
export async function GET(req:NextRequest){
 const s=await notificationSession(req);if(!s)return NextResponse.json({error:'Sessão expirada.'},{status:401});
 let uid=s.uid;const requested=req.nextUrl.searchParams.get('userId');
 if(requested&&requested!==s.uid){const[[actor]]:any=await getDbPool().query('SELECT role FROM users WHERE uid=? LIMIT 1',[s.uid]);if(!actor||!['admin','gerente'].includes(actor.role))return NextResponse.json({error:'Sem permissão para consultar outro colaborador.'},{status:403});const[[target]]:any=await getDbPool().query('SELECT uid FROM users WHERE uid=? LIMIT 1',[requested]);if(!target)return NextResponse.json({error:'Colaborador não encontrado.'},{status:404});uid=requested}
 const db=getDbPool(),fp=FINAL.map(()=>'?').join(','),ep=EVENTS.map(()=>'?').join(',');
 const[[period]]:any=await db.query("SELECT DATE_FORMAT(CURRENT_DATE,'%Y-%m-01') startDate,DATE_ADD(LAST_DAY(CURRENT_DATE),INTERVAL 1 DAY) endDate");
 const[[work]]:any=await db.query(`SELECT COUNT(DISTINCT CASE WHEN currentAssigneeId=? THEN id END) activePrimary,COUNT(DISTINCT CASE WHEN actionAssigneeId=? THEN id END) activeActions,COUNT(DISTINCT CASE WHEN (currentAssigneeId=? OR actionAssigneeId=?) AND dueDate<NOW() THEN id END) overdue,COUNT(DISTINCT CASE WHEN currentAssigneeId=? OR actionAssigneeId=? THEN id END) pending FROM posts WHERE currentStage NOT IN (${fp})`,[uid,uid,uid,uid,uid,uid,...FINAL]);
 const[distribution]:any=await db.query(`SELECT currentStage stage,COUNT(DISTINCT id) count FROM posts WHERE (currentAssigneeId=? OR actionAssigneeId=?) AND currentStage NOT IN (${fp}) GROUP BY currentStage ORDER BY count DESC`,[s.uid,uid,...FINAL]);
 const[[done]]:any=await db.query(`SELECT COUNT(*) completed FROM post_activity_events WHERE actorUserId=? AND eventType IN (${ep}) AND createdAt>=? AND createdAt<?`,[s.uid,...EVENTS,period.startDate,period.endDate]);
 const[[timing]]:any=await db.query(`SELECT AVG(TIMESTAMPDIFF(MINUTE,a.startedAt,a.endedAt)) averageStageTimeMinutes,SUM(CASE WHEN p.dueDate IS NOT NULL AND a.endedAt<=p.dueDate THEN 1 ELSE 0 END) onTime,SUM(CASE WHEN p.dueDate IS NOT NULL THEN 1 ELSE 0 END) deadlineSample FROM post_assignments a JOIN posts p ON p.id=a.postId WHERE a.assignedToUserId=? AND a.endedAt>=? AND a.endedAt<?`,[s.uid,period.startDate,period.endDate]);
 const[activityDays]:any=await db.query(`SELECT DISTINCT DATE_FORMAT(createdAt,'%Y-%m-%d') day FROM post_activity_events WHERE actorUserId=? AND eventType IN (${ep}) AND createdAt>=DATE_SUB(CURRENT_DATE,INTERVAL 90 DAY)`,[s.uid,...EVENTS]);const days=new Set(activityDays.map((r:any)=>r.day));let cursor=new Date(),streak=0,skippedToday=false;while(streak<65){const wd=cursor.getDay();if(wd!==0&&wd!==6){const key=cursor.toISOString().slice(0,10);if(!days.has(key)){if(streak===0&&!skippedToday){skippedToday=true;cursor.setDate(cursor.getDate()-1);continue}break}streak++}cursor.setDate(cursor.getDate()-1)}
 const sample=Number(timing.deadlineSample||0);return NextResponse.json({period:{start:period.startDate,end:period.endDate,key:'current_month'},workload:{activePrimary:Number(work.activePrimary||0),activeActions:Number(work.activeActions||0),overdue:Number(work.overdue||0),distribution:distribution.map((r:any)=>({stage:r.stage,count:Number(r.count)}))},performance:{completed:Number(done.completed||0),pending:Number(work.pending||0),onTimeRate:sample?Math.round(Number(timing.onTime||0)/sample*100):null,averageStageTimeMinutes:timing.averageStageTimeMinutes==null?null:Math.round(Number(timing.averageStageTimeMinutes)),streakWorkingDays:streak,ranking:null},formula:{completed:'marcos de workflow executados pelo colaborador no período',onTimeRate:'atribuições encerradas até o prazo / atribuições encerradas com prazo',averageStageTime:'tempo médio entre início e encerramento das atribuições'}})}
