import { dateKey, monthKey } from "./date";
import { buildItemsTaskMetaMap, isAutoGeneratedTitle } from "./utils";
import type { ContentItem, ContentType } from "./types";

/**
 * Reconcilia rascunhos com a cadência semanal: preserva conteúdo preenchido,
 * remove apenas rascunhos vazios excedentes e cria os que estiverem faltando.
 */
export function reconcilePostingDays(
  items: ContentItem[],
  newDays: number[],
  month: Date,
  weekdayFormats: Record<number, ContentType>,
  defaultProfile: string
): ContentItem[] {
  const year = month.getFullYear();
  const monthIdx = month.getMonth();
  const daysInMonth = new Date(year, monthIdx + 1, 0).getDate();
  const targetCounts = new Map<string, number>();

  for (let day = 1; day <= daysInMonth; day++) {
    const d = new Date(year, monthIdx, day);
    const weekdayCount = newDays.filter((n) => n === d.getDay()).length;
    if (weekdayCount > 0) {
      targetCounts.set(dateKey(d), weekdayCount);
    }
  }

  const currentMonthPrefix = monthKey(month);
  const existingThisMonth = items.filter((it) => it.date.startsWith(currentMonthPrefix));
  const otherMonthItems = items.filter((it) => !it.date.startsWith(currentMonthPrefix));

  const updatedMonthItems: ContentItem[] = [];
  const currentCounts = new Map<string, number>();

  for (const item of existingThisMonth) {
    const target = targetCounts.get(item.date) || 0;
    const current = currentCounts.get(item.date) || 0;

    const isBlankDraft =
      item.status === "Ideia" &&
      !item.imageUrl &&
      (item.title === "Publicação" || item.title === "Nova publicação") &&
      !item.caption &&
      !item.visual;

    if (!isBlankDraft || current < target) {
      updatedMonthItems.push(item);
      currentCounts.set(item.date, current + 1);
    }
  }

  for (let day = 1; day <= daysInMonth; day++) {
    const d = new Date(year, monthIdx, day);
    const key = dateKey(d);
    const target = targetCounts.get(key) || 0;
    let current = currentCounts.get(key) || 0;

    while (current < target) {
      const dayOfWeek = d.getDay();
      const defaultTypeForDay = weekdayFormats[dayOfWeek] || "Feed e Story";
      const newItem: ContentItem = {
        id: crypto.randomUUID(),
        date: key,
        title: defaultProfile || "Publicação",
        type: defaultTypeForDay,
        status: "Ideia",
        channel: "Instagram",
        profile: defaultProfile,
        isCollab: false,
        collabProfile: "",
        objective: "",
        head: "",
        subhead: "",
        caption: "",
        visual: "",
        imageUrl: "",
        funnelStage: "Topo",
        internalNotes: "",
      };
      updatedMonthItems.push(newItem);
      current++;
    }
  }

  updatedMonthItems.sort((a, b) => a.date.localeCompare(b.date));
  const allItems = [...otherMonthItems, ...updatedMonthItems];

  const metaMap = buildItemsTaskMetaMap(allItems);
  return allItems.map((entry) => {
    if (isAutoGeneratedTitle(entry.title, entry.profile)) {
      const meta = metaMap.get(entry.id);
      if (meta) {
        return { ...entry, title: meta.autoTitle };
      }
    }
    return entry;
  });
}
