import "server-only";
import { createHash, randomUUID } from "crypto";
import { NextRequest } from "next/server";
import { getDbPool } from "./db";

export const NOTIFICATION_CATEGORIES=["clients","posts","artwork","comments","approvals","assignments","calendar","integrations","security"] as const;
export type NotificationCategory=typeof NOTIFICATION_CATEGORIES[number];
export async function notificationSession(req:NextRequest){const token=req.cookies.get("cp_session")?.value;if(!token)return null;const [result]=await getDbPool().query("SELECT u.id uid,u.name displayName FROM user_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>NOW() AND s.revoked_at IS NULL AND u.active=TRUE LIMIT 1",[createHash("sha256").update(token).digest("hex")]);return (result as any[])[0]||null;}
export async function ensureNotificationPreferences(userId:string){for(const category of NOTIFICATION_CATEGORIES)await getDbPool().execute("INSERT IGNORE INTO notification_preferences (user_id,notification_type,in_app_enabled,push_enabled,email_enabled) VALUES (?,?,TRUE,TRUE,FALSE)",[userId,category]);}
export function buildNotificationRoute(input:{entityType:string;entityId?:string|number|null;clientId?:string|null;metadata?:Record<string,unknown>|null}){const query=new URLSearchParams();if(input.clientId)query.set("clientId",input.clientId);if(input.entityType==="work_item"&&input.entityId!=null)query.set("workItemId",String(input.entityId));return "/?"+query.toString();}
export function sanitizeNotificationRoute(route:string|null|undefined){if(!route||!route.startsWith("/")||route.startsWith("//"))return null;try{const parsed=new URL(route,"http://internal.local");return parsed.origin==="http://internal.local"?parsed.pathname+parsed.search+parsed.hash:null;}catch{return null;}}
type EventInput={actorUserId?:string|null;type:string;category:NotificationCategory;entityType:string;entityId?:string|number|null;clientId?:string|null;title:string;body:string;route:string;recipientUserIds:string[];dedupeKey?:string|null};
export async function createNotificationEvent(input:EventInput){const recipients=[...new Set(input.recipientUserIds)].filter(Boolean).filter((id)=>id!==input.actorUserId);if(!recipients.length)return null;const db=getDbPool();for(const recipient of recipients){const notificationId=randomUUID();const data={category:input.category,entityType:input.entityType,entityId:input.entityId??null,clientId:input.clientId??null,title:input.title,body:input.body,route:sanitizeNotificationRoute(input.route)||buildNotificationRoute(input)};await db.execute("INSERT IGNORE INTO notifications (id,recipient_user_id,actor_user_id,type,work_item_id,data_json,deduplication_key) VALUES (?,?,?,?,?,?,?)",[notificationId,recipient,input.actorUserId||null,input.type,input.entityType==="work_item"?String(input.entityId||"")||null:null,JSON.stringify(data),input.dedupeKey?`${input.dedupeKey}:${recipient}`:null]);}return true;}
export async function resolvePostRecipients(clientId:string,assigneeId?:string|null){const [result]=await getDbPool().query(`SELECT DISTINCT u.id uid FROM users u LEFT JOIN client_members cm ON cm.user_id=u.id AND cm.client_id=? AND cm.removed_at IS NULL LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id WHERE u.id=? OR cm.id IS NOT NULL OR r.key_name IN ('ADMIN','MANAGEMENT')`,[clientId,assigneeId||""]);return (result as any[]).map((row)=>row.uid);}
