import {createHash} from "crypto";import {getDbPool,parseJson} from "./db";
type DbRow=Record<string,any>;export type ReviewDataError={error:string;status:number};export function isReviewDataError(value:unknown):value is ReviewDataError{return Boolean(value&&typeof value==="object"&&"error" in value);}
const tokenHash=(token:string)=>createHash("sha256").update(token).digest("hex");
function safeTokenData(row:DbRow){return{id:row.public_token,clientId:row.client_id,workItemId:row.work_item_id,month:row.period_key||new Date().toISOString().slice(0,7),status:String(row.status||"PENDING").toLowerCase(),createdAt:new Date(row.created_at).getTime(),expiresAt:new Date(row.expires_at).getTime(),clientNote:row.client_note||null};}
export async function validateReviewToken(token:string):Promise<DbRow|ReviewDataError>{if(!token)return{error:"Token de revisão inválido.",status:404};const [result]=await getDbPool().query("SELECT * FROM public_approval_tokens WHERE token_hash=?",[tokenHash(token)]);const row=(result as DbRow[])[0];if(!row)return{error:"Token de revisão inválido.",status:404};if(row.revoked_at)return{error:"Token de revisão revogado.",status:410};if(new Date(row.expires_at).getTime()<Date.now())return{error:"Token de revisão expirado.",status:410};return{...row,public_token:token,clientId:row.client_id,workItemId:row.work_item_id,month:row.period_key};}
export async function validateReviewPost(token:string,postId:string|number){const tokenData=await validateReviewToken(token);if(isReviewDataError(tokenData))return tokenData;const [result]=await getDbPool().query(`SELECT w.id FROM work_items w WHERE w.id=? AND w.client_id=? AND w.deleted_at IS NULL AND (w.id=? OR w.parent_id=?)`,[postId,tokenData.client_id,tokenData.work_item_id,tokenData.work_item_id]);return(result as DbRow[])[0]?tokenData:{error:"Conteúdo não pertence a esta revisão.",status:404} as ReviewDataError;}
async function buildReviewData(clientId:string,period:string,tokenData:DbRow|null=null,rootWorkItemId?:string){const db=getDbPool();const [clientResult]=await db.query("SELECT * FROM clients WHERE id=? AND archived_at IS NULL",[clientId]);const client=(clientResult as DbRow[])[0];if(!client)return{error:"Cliente associado não encontrado.",status:404} as ReviewDataError;const params:any[]=[clientId];let root="";if(rootWorkItemId){root="AND (w.id=? OR w.parent_id=?)";params.push(rootWorkItemId,rootWorkItemId);}else if(/^\d{4}-\d{2}$/.test(period)){root="AND w.due_at>=? AND w.due_at<DATE_ADD(?,INTERVAL 1 MONTH)";params.push(`${period}-01`,`${period}-01`);}const [items]=await db.query(`SELECT w.id,w.client_id clientId,DATE_FORMAT(COALESCE(w.due_at,w.created_at),'%Y-%m-%d') date,w.title,w.status,w.due_at deadline,ci.head,ci.subhead,ci.caption,ci.objective,ci.hashtags,ci.funnel_stage funnelStage,ci.editorial_json,sc.key_name channel,cf.key_name type FROM work_items w JOIN content_items ci ON ci.work_item_id=w.id LEFT JOIN social_channels sc ON sc.id=ci.channel_id LEFT JOIN content_formats cf ON cf.id=ci.format_id WHERE w.client_id=? AND w.deleted_at IS NULL ${root} ORDER BY COALESCE(w.due_at,w.created_at)`,params);const workItems=items as DbRow[];const owners=await db.query(`SELECT DISTINCT u.name displayName,r.key_name role FROM client_members cm JOIN users u ON u.id=cm.user_id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id WHERE cm.client_id=? AND cm.removed_at IS NULL`,[clientId]).then(([value])=>value as DbRow[]);return{tokenData:tokenData?safeTokenData(tokenData):{id:`presentation-${clientId}-${period}`,clientId,month:period,status:"public",createdAt:null,expiresAt:null},client:{id:client.id,name:client.display_name,displayName:client.display_name,logoUrl:client.logo_url,segment:client.segment,owners:owners.map(()=>""),socialLinks:{},instagramStats:{},config:parseJson(client.strategy_json,{})},owners:owners.map(owner=>({...owner,role:String(owner.role||"").toLowerCase()})),posts:await Promise.all(workItems.map(async work=>{const comments=tokenData?await db.query("SELECT c.id,c.work_item_id postId,COALESCE(u.name,'Cliente') authorName,'cliente' authorRole,c.body content,c.created_at createdAt FROM comments c LEFT JOIN users u ON u.id=c.user_id WHERE c.work_item_id=? AND c.deleted_at IS NULL ORDER BY c.created_at",[work.id]).then(([value])=>value):[];const editorial=parseJson(work.editorial_json,{});return{...work,...editorial,feedImages:editorial.feedImages||[],comments};}))};}
export async function getReviewData(token:string){const tokenData=await validateReviewToken(token);return isReviewDataError(tokenData)?tokenData:buildReviewData(tokenData.client_id,tokenData.period_key||"",tokenData,tokenData.work_item_id);}
export async function getPresentationData(clientId:string,month:string){if(!clientId||!/^\d{4}-\d{2}$/.test(month))return{error:"Apresentação inválida.",status:400} as ReviewDataError;return buildReviewData(clientId,month);}
