import type { ContentItem } from "./types";

/** Agrupa operações pequenas e puras usadas por mais de um componente. */

/** Descarta valores falsos e une as classes CSS restantes com um espaço. */
export function cn(...inputs: (string | undefined | null | false)[]) {
  return inputs.filter(Boolean).join(" ");
}

export interface ItemTaskMeta {
  tag: string; // Ex: "Arte 01", "Arte 02", "01 Collab"
  autoTitle: string; // Ex: "Arte 01 @ativa_vet", "Arte 01 @ativahospitalar", "01 Collab @ativa_vet + @ativahospitalar"
  seqNumber: number;
  isCollab: boolean;
  profile: string;
}

/**
 * Computa a numeração e identificação de tarefas para os posts do calendário.
 * Itens são ordenados cronologicamente por data, depois por orderIndex e id.
 * O contador é individualizado por perfil e por collab, permitindo que no mesmo dia
 * coexistam:
 * - "Arte 01 @ativa_vet"
 * - "Arte 01 @ativahospitalar"
 * - "01 Collab @ativa_vet + @ativahospitalar"
 */
export function buildItemsTaskMetaMap(items: ContentItem[]): Map<string, ItemTaskMeta> {
  const sorted = [...items].sort((a, b) => {
    if (a.date !== b.date) return a.date.localeCompare(b.date);
    const orderA = a.orderIndex ?? 0;
    const orderB = b.orderIndex ?? 0;
    if (orderA !== orderB) return orderA - orderB;
    return a.id.localeCompare(b.id);
  });

  const profileCounters = new Map<string, number>();
  let collabCounter = 0;
  let unassignedCounter = 0;

  const result = new Map<string, ItemTaskMeta>();

  for (const item of sorted) {
    if (item.isCollab) {
      collabCounter++;
      const numStr = String(collabCounter).padStart(2, "0");
      const tag = `${numStr} Collab`;
      const p1 = (item.profile || "").trim();
      const p2 = (item.collabProfile || "").trim();
      const collabs = p1 && p2 ? `${p1} + ${p2}` : (p1 || p2 || "Collab");
      const autoTitle = `${numStr} Collab ${collabs}`.trim();
      result.set(item.id, {
        tag,
        autoTitle,
        seqNumber: collabCounter,
        isCollab: true,
        profile: collabs,
      });
    } else if (item.profile && item.profile.trim()) {
      const p = item.profile.trim();
      const count = (profileCounters.get(p) || 0) + 1;
      profileCounters.set(p, count);
      const numStr = String(count).padStart(2, "0");
      const tag = `Arte ${numStr}`;
      const autoTitle = `Arte ${numStr} ${p}`;
      result.set(item.id, {
        tag,
        autoTitle,
        seqNumber: count,
        isCollab: false,
        profile: p,
      });
    } else {
      unassignedCounter++;
      const numStr = String(unassignedCounter).padStart(2, "0");
      const tag = `Arte ${numStr}`;
      const autoTitle = `Arte ${numStr}`;
      result.set(item.id, {
        tag,
        autoTitle,
        seqNumber: unassignedCounter,
        isCollab: false,
        profile: "",
      });
    }
  }

  return result;
}

export function getItemTaskMeta(item: ContentItem, allItems: ContentItem[]): ItemTaskMeta {
  const map = buildItemsTaskMetaMap(allItems);
  const found = map.get(item.id);
  if (found) return found;

  const numStr = "01";
  if (item.isCollab) {
    const p1 = (item.profile || "").trim();
    const p2 = (item.collabProfile || "").trim();
    const collabs = p1 && p2 ? `${p1} + ${p2}` : (p1 || p2 || "Collab");
    return {
      tag: `${numStr} Collab`,
      autoTitle: `${numStr} Collab ${collabs}`.trim(),
      seqNumber: 1,
      isCollab: true,
      profile: collabs,
    };
  }

  if (item.profile && item.profile.trim()) {
    const p = item.profile.trim();
    return {
      tag: `Arte ${numStr}`,
      autoTitle: `Arte ${numStr} ${p}`,
      seqNumber: 1,
      isCollab: false,
      profile: p,
    };
  }

  return {
    tag: `Arte ${numStr}`,
    autoTitle: `Arte ${numStr}`,
    seqNumber: 1,
    isCollab: false,
    profile: "",
  };
}

/** Verifica se um título é padrão/automático do sistema (e portanto pode ser recalculado ao trocar perfil/collab) */
export function isAutoGeneratedTitle(t?: string, currentProfile?: string): boolean {
  if (!t) return true;
  const trimmed = t.trim();
  if (
    trimmed === "" ||
    trimmed === "Nova publicação" ||
    trimmed === "Publicação" ||
    trimmed === "Publicação sem título"
  ) {
    return true;
  }
  if (currentProfile) {
    if (trimmed === currentProfile || trimmed === `${currentProfile} (Collab)`) return true;
    if (trimmed.startsWith(`${currentProfile} + `)) return true;
  }
  // Casa com padrões como "Arte 01 @perfil", "Arte 02", "01 Collab @perfil + @outro", etc.
  if (/^Arte\s+\d+(\s+@?.*)?$/i.test(trimmed)) return true;
  if (/^\d+\s+Collab(\s+@?.*)?$/i.test(trimmed)) return true;
  if (/^Collab\s+\d+(\s+@?.*)?$/i.test(trimmed)) return true;
  return false;
}

