import { randomBytes, randomUUID, createHash } from "crypto";
import { NextRequest, NextResponse } from "next/server";
import { body, toMysqlDateTime } from "./api-core/context";
import { err, ok } from "./api-response";
import { getDbPool, parseJson, rows } from "./db";

async function addEvent(connection:any,itemId:string,userId:string,type:string,data:unknown){await connection.query("INSERT INTO work_item_events (work_item_id,actor_id,event_type,data_json) VALUES (?,?,?,?)",[itemId,userId,type,JSON.stringify(data)]);}
async function item(id:string){return (await rows("SELECT * FROM work_items WHERE id=? AND deleted_at IS NULL",[id]))[0];}

async function content(req:NextRequest,id:string,userId:string,method:string){
  if(method==="GET"){const value=(await rows(`SELECT ci.*,sc.key_name channel,cf.key_name format FROM content_items ci LEFT JOIN social_channels sc ON sc.id=ci.channel_id LEFT JOIN content_formats cf ON cf.id=ci.format_id WHERE ci.work_item_id=?`,[id]))[0];return ok(value?{...value,editorial_json:parseJson(value.editorial_json,{})}:null);}
  const input=await body(req);const work=await item(id);if(!work||work.type!=="TASK")return err("Conteúdo só pode ser associado a TASK.",422);const db=await getDbPool().getConnection();
  try{await db.beginTransaction();const existing=(await db.query("SELECT * FROM content_items WHERE work_item_id=? FOR UPDATE",[id]) as any)[0][0];const channel=input.channel?(await db.query("SELECT id FROM social_channels WHERE key_name=?",[String(input.channel).toUpperCase()]) as any)[0][0]:null;const format=input.format?(await db.query("SELECT id FROM content_formats WHERE key_name=?",[String(input.format).toUpperCase()]) as any)[0][0]:null;const contentId=existing?.id||randomUUID();if(existing)await db.query("UPDATE content_items SET head=?,subhead=?,caption=?,objective=?,hashtags=?,internal_notes=?,funnel_stage=?,channel_id=?,format_id=?,editorial_json=? WHERE id=?",[input.head||null,input.subhead||null,input.caption||null,input.objective||null,input.hashtags||null,input.internalNotes||null,input.funnelStage||null,channel?.id||null,format?.id||null,JSON.stringify(input.editorial||{}),contentId]);else await db.query("INSERT INTO content_items (id,work_item_id,head,subhead,caption,objective,hashtags,internal_notes,funnel_stage,channel_id,format_id,editorial_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",[contentId,id,input.head||null,input.subhead||null,input.caption||null,input.objective||null,input.hashtags||null,input.internalNotes||null,input.funnelStage||null,channel?.id||null,format?.id||null,JSON.stringify(input.editorial||{})]);const [[version]]=await db.query("SELECT COALESCE(MAX(version_number),0)+1 number FROM content_versions WHERE content_item_id=?",[contentId]) as any;const versionId=randomUUID();const versionNumber=Number(version.number);await db.query("INSERT INTO content_versions (id,content_item_id,version_number,snapshot_json,created_by) VALUES (?,?,?,?,?)",[versionId,contentId,versionNumber,JSON.stringify(input),userId]);await addEvent(db,id,userId,existing?"CONTENT_UPDATED":"CONTENT_CREATED",{contentId,versionId,version:versionNumber});await db.commit();return ok({id:contentId,versionId,version:versionNumber});}catch(error:any){await db.rollback();return err(error.message,500);}finally{db.release();}
}

async function publications(req:NextRequest,id:string,userId:string,method:string){const contentItem=(await rows("SELECT id FROM content_items WHERE work_item_id=?",[id]))[0];if(!contentItem)return err("Conteúdo não encontrado.",404);if(method==="GET")return ok(await rows(`SELECT p.*,sc.key_name channel FROM publications p JOIN social_channels sc ON sc.id=p.channel_id WHERE p.content_item_id=? ORDER BY p.scheduled_at`,[contentItem.id]));const input=await body(req);const channel=(await rows("SELECT id FROM social_channels WHERE key_name=?",[String(input.channel||"").toUpperCase()]))[0];if(!channel)return err("Canal inválido.",422);const publicationId=String(input.id||randomUUID());await getDbPool().query(`INSERT INTO publications (id,content_item_id,channel_id,scheduled_at,published_at,status,external_post_id,url,verification_status,verified_by,verified_at,verification_notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE scheduled_at=VALUES(scheduled_at),published_at=VALUES(published_at),status=VALUES(status),external_post_id=VALUES(external_post_id),url=VALUES(url),verification_status=VALUES(verification_status),verified_by=VALUES(verified_by),verified_at=VALUES(verified_at),verification_notes=VALUES(verification_notes)`,[publicationId,contentItem.id,channel.id,toMysqlDateTime(input.scheduledAt),toMysqlDateTime(input.publishedAt),input.status||"DRAFT",input.externalPostId||null,input.url||null,input.verificationStatus||"PENDING",input.verificationStatus&&input.verificationStatus!=="PENDING"?userId:null,input.verificationStatus&&input.verificationStatus!=="PENDING"?new Date():null,input.verificationNotes||null]);return ok({id:publicationId});}

async function photoJob(req:NextRequest,id:string,method:string){if(method==="GET")return ok((await rows("SELECT * FROM photo_jobs WHERE work_item_id=?",[id]))[0]||null);const work=await item(id);if(!work||!["DEMAND","TASK"].includes(work.type))return err("Photo job exige DEMAND ou TASK.",422);const input=await body(req);const keys=["capturedCount","selectedCount","targetEditCount","editedCount","exportedCount","deliveredCount"];const values=keys.map((key)=>Math.max(0,Math.floor(Number(input[key]||0))));if(values.slice(1).some((value,index)=>value>values[index]))return err("As contagens não podem exceder a etapa anterior.",422);const photoId=String(input.id||randomUUID());await getDbPool().query(`INSERT INTO photo_jobs (id,work_item_id,captured_count,selected_count,target_edit_count,edited_count,exported_count,delivered_count) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE captured_count=VALUES(captured_count),selected_count=VALUES(selected_count),target_edit_count=VALUES(target_edit_count),edited_count=VALUES(edited_count),exported_count=VALUES(exported_count),delivered_count=VALUES(delivered_count)`,[photoId,id,...values]);const target=values[2]||values[1];const progress=target?Math.min(100,Math.round(values[3]/target*100)):0;await getDbPool().query("UPDATE work_items SET progress=? WHERE id=?",[progress,id]);return ok({id:photoId,progress});}

const allowedExternal:Record<string,string[]>={PLANNED:["READY","CANCELLED"],READY:["DEPARTED","CANCELLED"],DEPARTED:["IN_TRANSIT"],IN_TRANSIT:["ARRIVED"],ARRIVED:["IN_PROGRESS"],IN_PROGRESS:["RETURNING","FINISHED"],RETURNING:["FINISHED"],FINISHED:[],CANCELLED:[]};
async function externalOperation(req:NextRequest,id:string,userId:string,method:string,action?:string){
  const work=await item(id);if(!work||!["DEMAND","TASK"].includes(work.type))return err("Operação externa exige DEMAND ou TASK.",422);
  const current=(await rows("SELECT * FROM external_operations WHERE work_item_id=?",[id]))[0];
  if(!action&&method==="GET")return ok(current||null);
  const input=await body(req);
  if(!action){const operationId=current?.id||randomUUID();await getDbPool().query(`INSERT INTO external_operations (id,work_item_id,operation_type,title,objective,briefing,location_name,address,latitude,longitude,geofence_radius_meters,scheduled_start,scheduled_end,status,tracking_enabled,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE operation_type=VALUES(operation_type),title=VALUES(title),objective=VALUES(objective),briefing=VALUES(briefing),location_name=VALUES(location_name),address=VALUES(address),latitude=VALUES(latitude),longitude=VALUES(longitude),geofence_radius_meters=VALUES(geofence_radius_meters),scheduled_start=VALUES(scheduled_start),scheduled_end=VALUES(scheduled_end),tracking_enabled=VALUES(tracking_enabled)`,[operationId,id,String(input.operationType||"OTHER").toUpperCase(),input.title||work.title,input.objective||null,input.briefing||null,input.locationName||null,input.address||null,input.latitude||null,input.longitude||null,input.geofenceRadiusMeters||null,toMysqlDateTime(input.scheduledStart),toMysqlDateTime(input.scheduledEnd),current?.status||"PLANNED",Boolean(input.trackingEnabled),userId]);return ok({id:operationId});}
  if(!current)return err("Operação externa não encontrada.",404);
  if(action==="transition"){
    const next=String(input.status||"").toUpperCase();if(!allowedExternal[current.status]?.includes(next))return err("Transição operacional inválida.",422);
    if(next==="FINISHED"){const blockers=await rows("SELECT id FROM external_operation_plan_items WHERE external_operation_id=? AND blocking=TRUE AND completed_at IS NULL",[current.id]);if(blockers.length)return err("Há itens bloqueantes pendentes.",409);}
    const fields=["status=?"],values:any[]=[next];if(next==="IN_PROGRESS"&&!current.actual_start)fields.push("actual_start=NOW()");if(next==="FINISHED")fields.push("actual_end=NOW()","tracking_ended_at=IF(tracking_enabled,NOW(),tracking_ended_at)");if(next==="DEPARTED"&&current.tracking_enabled)fields.push("tracking_started_at=NOW()");values.push(current.id);const db=await getDbPool().getConnection();try{await db.beginTransaction();await db.query(`UPDATE external_operations SET ${fields.join(",")} WHERE id=?`,values);await db.query("INSERT INTO external_operation_events (external_operation_id,actor_id,event_type,data_json) VALUES (?,?,?,?)",[current.id,userId,next,JSON.stringify(input.data||{})]);await addEvent(db,id,userId,next==="FINISHED"?"EXTERNAL_OPERATION_FINISHED":"EXTERNAL_OPERATION_STATUS_CHANGED",{status:next});await db.commit();return ok({success:true,status:next});}catch(error:any){await db.rollback();return err(error.message,500);}finally{db.release();}
  }
  if(action==="locations"&&method==="POST"){if(!current.tracking_enabled||current.tracking_ended_at)return err("Tracking não está ativo.",409);await getDbPool().query("INSERT INTO external_operation_locations (external_operation_id,user_id,latitude,longitude,accuracy_meters,captured_at) VALUES (?,?,?,?,?,?)",[current.id,userId,input.latitude,input.longitude,input.accuracyMeters||null,toMysqlDateTime(input.capturedAt)||new Date()]);return ok({success:true},201);}
  if(action==="plan-items"){
    if(method==="GET")return ok(await rows("SELECT * FROM external_operation_plan_items WHERE external_operation_id=? ORDER BY category,sort_order",[current.id]));
    if(method==="POST"){const planId=randomUUID();await getDbPool().query("INSERT INTO external_operation_plan_items (id,external_operation_id,title,description,priority,required,blocking,assigned_to,category,sort_order) VALUES (?,?,?,?,?,?,?,?,?,?)",[planId,current.id,input.title,input.description||null,input.priority||"NORMAL",Boolean(input.required),Boolean(input.blocking),input.assignedTo||null,input.category||"GENERAL",Number(input.sortOrder||0)]);return ok({id:planId},201);}
    await getDbPool().query("UPDATE external_operation_plan_items SET completed_at=?,completed_by=? WHERE id=? AND external_operation_id=?",[input.completed?new Date():null,input.completed?userId:null,input.id,current.id]);return ok({success:true});
  }
  if(action==="incidents"){if(method==="GET")return ok(await rows("SELECT * FROM external_operation_incidents WHERE external_operation_id=? ORDER BY created_at DESC",[current.id]));const incidentId=randomUUID();await getDbPool().query("INSERT INTO external_operation_incidents (id,external_operation_id,reported_by,severity,title,description) VALUES (?,?,?,?,?,?)",[incidentId,current.id,userId,input.severity||"NORMAL",input.title,input.description||null]);return ok({id:incidentId},201);}
  return err("Ação de operação externa inválida.",404);
}

async function approvals(req:NextRequest,id:string,userId:string,method:string,action?:string){
  if(method==="GET"&&!action)return ok(await rows(`SELECT af.*,cv.version_number FROM approval_flows af LEFT JOIN content_versions cv ON cv.id=af.content_version_id WHERE af.work_item_id=? ORDER BY af.created_at DESC`,[id]));const input=await body(req);
  if(!action){const flowId=randomUUID();await getDbPool().query("INSERT INTO approval_flows (id,work_item_id,content_version_id,created_by) VALUES (?,?,?,?)",[flowId,id,input.contentVersionId||null,userId]);for(let index=0;index<(input.steps||[]).length;index+=1){const step=input.steps[index];await getDbPool().query("INSERT INTO approval_steps (id,approval_flow_id,name,approver_user_id,approver_role_id,sort_order) VALUES (?,?,?,?,?,?)",[randomUUID(),flowId,step.name,step.approverUserId||null,step.approverRoleId||null,index]);}return ok({id:flowId},201);}
  if(action==="decision"){const step=(await rows(`SELECT s.*,f.work_item_id,f.content_version_id FROM approval_steps s JOIN approval_flows f ON f.id=s.approval_flow_id WHERE s.id=?`,[input.stepId]))[0];if(!step||step.work_item_id!==id)return err("Etapa não encontrada.",404);const decision=String(input.decision||"").toUpperCase();if(!["APPROVED","CHANGES_REQUESTED","REJECTED"].includes(decision))return err("Decisão inválida.",422);await getDbPool().query("INSERT INTO approval_decisions (id,approval_step_id,decided_by,decision,comment,content_version_id) VALUES (?,?,?,?,?,?)",[randomUUID(),step.id,userId,decision,input.comment||null,step.content_version_id]);await getDbPool().query("UPDATE approval_steps SET status=? WHERE id=?",[decision,step.id]);if(decision!=="APPROVED")await getDbPool().query("UPDATE approval_flows SET status=?,completed_at=NOW() WHERE id=?",[decision,step.approval_flow_id]);return ok({success:true});}
  if(action==="public-token"){const raw=randomBytes(32).toString("base64url");const tokenId=randomUUID();await getDbPool().query("INSERT INTO public_approval_tokens (id,token_hash,client_id,work_item_id,content_version_id,approval_flow_id,expires_at,created_by) VALUES (?,?,?,?,?,?,?,?)",[tokenId,createHash("sha256").update(raw).digest("hex"),input.clientId,id,input.contentVersionId||null,input.approvalFlowId||null,toMysqlDateTime(input.expiresAt),userId]);return ok({id:tokenId,token:raw},201);}
  return err("Ação de aprovação inválida.",404);
}

export async function handleCapability(req:NextRequest,id:string,segments:string[],method:string,userId:string):Promise<NextResponse|null>{const [resource,action]=segments;if(resource==="content"&&["GET","PUT","POST"].includes(method))return content(req,id,userId,method);if(resource==="content-versions"&&method==="GET")return ok(await rows(`SELECT cv.id,cv.version_number versionNumber,cv.snapshot_json snapshot,cv.created_at createdAt,u.name createdByName FROM content_versions cv JOIN content_items ci ON ci.id=cv.content_item_id LEFT JOIN users u ON u.id=cv.created_by WHERE ci.work_item_id=? ORDER BY cv.version_number DESC`,[id]));if(resource==="publications"&&["GET","POST","PATCH"].includes(method))return publications(req,id,userId,method);if(resource==="photo-job"&&["GET","PUT","POST"].includes(method))return photoJob(req,id,method);if(resource==="external-operation"&&["GET","PUT","POST","PATCH"].includes(method))return externalOperation(req,id,userId,method,action);if(resource==="approvals"&&["GET","POST"].includes(method))return approvals(req,id,userId,method,action);return null;}
