import { presentationFormatLabel, presentationMetrics, PresentationViewModel } from "../../lib/presentation-model";

export function StaticPresentationDocument({ model, mediaUrl }: { model: PresentationViewModel; mediaUrl?: (assetId: string, fallback: string) => string }) {
  const strategy = Object.entries({ Segmento: model.estrategia.segmento, "Tom de voz": model.estrategia.tomDeVoz, "Público-alvo": model.estrategia.publicoAlvo, Observações: model.estrategia.observacoes }).filter(([, value]) => value);
  const metrics=presentationMetrics(model);
  return <main className="pdf-document">
    <section className="pdf-page pdf-cover"><div>{model.cliente.logoUrl&&model.cliente.logoState==="ready" ? <div className="pdf-logo"><div className="pdf-initials">{model.cliente.nome.slice(0,2).toUpperCase()}</div><img data-required="false" src={model.cliente.logoAssetId&&mediaUrl?mediaUrl(model.cliente.logoAssetId,model.cliente.logoUrl):model.cliente.logoUrl} alt={`Logo de ${model.cliente.nome}`} /></div> : <div className="pdf-initials">{model.cliente.nome.slice(0,2).toUpperCase()}</div>}<p>Planejamento de conteúdo</p><h1>{model.cliente.nome}</h1><h2>{model.competenciaLabel}</h2></div></section>
    <section className="pdf-page"><h2>Resumo do planejamento</h2><dl><div><dt>Volume mensal</dt><dd>{metrics.total} {metrics.total===1?"publicação":"publicações"}</dd></div><div><dt>Formatos</dt><dd>Feed {metrics.formatPercent.feed}% · Story {metrics.formatPercent.story}% · Carrossel {metrics.formatPercent.carousel}% · Reel {metrics.formatPercent.reel}%</dd></div><div><dt>Etapas do funil informadas</dt><dd>Topo {metrics.funnelPercent.topo}% · Meio {metrics.funnelPercent.meio}% · Fundo {metrics.funnelPercent.fundo}%</dd></div>{strategy.map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{model.estrategia.colunasDeConteudo.length ? <><h3>Colunas de conteúdo</h3><ul>{model.estrategia.colunasDeConteudo.map(item => <li key={item}>{item}</li>)}</ul></> : null}</section>
    <section className="pdf-page"><h2>Calendário editorial</h2>{model.posts.length ? <table><thead><tr><th>Data</th><th>Formato</th><th>Conteúdo</th><th>Objetivo</th></tr></thead><tbody>{model.posts.map(post => <tr key={post.id}><td>{new Intl.DateTimeFormat("pt-BR").format(new Date(`${post.data}T12:00:00`))}</td><td>{presentationFormatLabel(post.formato)}</td><td>{post.titulo || "Não informado"}</td><td>{post.objetivo || "Não informado"}</td></tr>)}</tbody></table> : <p>Nenhuma publicação cadastrada para esta competência.</p>}</section>
    {model.posts.map((post,index) => { const readyMedia=post.midias.filter(item=>item.state==="ready"&&item.url); return <section className="pdf-page pdf-post" key={post.id}><header><span>Publicação {String(index+1).padStart(2,"0")}</span><span>{new Intl.DateTimeFormat("pt-BR").format(new Date(`${post.data}T12:00:00`))} · {presentationFormatLabel(post.formato)}</span></header><h2>{post.titulo || "Não informado"}</h2>{post.subtitulo ? <h3>{post.subtitulo}</h3> : null}{readyMedia.length ? <div className="pdf-media-grid">{readyMedia.map(item => <figure key={item.ordem}><img data-required={item.required?"true":"false"} src={item.assetId && mediaUrl ? mediaUrl(item.assetId,item.url!):item.url!} alt={`Peça ${item.ordem} de ${post.titulo || "publicação"}`} /><figcaption>Peça {item.ordem} de {post.midias.length}</figcaption></figure>)}</div> : <p className="pdf-warning">Mídia não cadastrada ou indisponível.</p>}{post.formato==="reel"&&post.videoUrl?<p><a href={post.videoUrl}>Abrir vídeo original</a></p>:null}<dl>{post.legenda ? <div><dt>Legenda</dt><dd className="pdf-long-text">{post.legenda}</dd></div> : null}{post.objetivo ? <div><dt>Objetivo</dt><dd>{post.objetivo}</dd></div> : null}{post.tema ? <div><dt>Tema</dt><dd>{post.tema}</dd></div> : null}{post.roteiro ? <div><dt>Roteiro</dt><dd className="pdf-long-text">{post.roteiro}</dd></div> : null}</dl></section>})}
    <div id="pdf-render-ready" data-ready="true" />
  </main>;
}
