"use client";

import {
  CalendarDays,
  GripVertical,
  Users,
  ChevronUp,
  ChevronDown,
  Plus,
} from "lucide-react";
import type { ContentItem } from "../../lib/types";
import { isAutoGeneratedTitle } from "../../lib/utils";

export interface CalendarDayPanelProps {
  selectedDate: string;
  selectedId: string | null;
  selectedDayPosts: ContentItem[];
  taskMetaMap: Map<string, any>;
  dragSource: {
    type: "day" | "post";
    sourceDate: string;
    postId?: string;
    postIds?: string[];
    label?: string;
  } | null;
  dragOverPostId: string | null;
  dragOverPosition: "before" | "after" | null;
  onSelect: (item: ContentItem) => void;
  onCreate: (date: string) => void;
  onReorderPosts?: (sourcePostId: string, targetPostId: string, position?: "before" | "after") => void;
  onPostTabDragStart: (e: React.DragEvent, post: ContentItem, label: string) => void;
  onDragEnd: () => void;
  onPostTabDragOver: (e: React.DragEvent, targetPostId: string) => void;
  onPostTabDragLeave: (e: React.DragEvent, targetPostId: string) => void;
  onPostTabDrop: (e: React.DragEvent, targetPost: ContentItem) => void;
}

export function CalendarDayPanel({
  selectedDate,
  selectedId,
  selectedDayPosts,
  taskMetaMap,
  dragSource,
  dragOverPostId,
  dragOverPosition,
  onSelect,
  onCreate,
  onReorderPosts,
  onPostTabDragStart,
  onDragEnd,
  onPostTabDragOver,
  onPostTabDragLeave,
  onPostTabDrop,
}: CalendarDayPanelProps) {
  const formatSelectedDateShort = (dateStr: string) => {
    try {
      const d = new Date(`${dateStr}T12:00:00`);
      return d.toLocaleDateString("pt-BR", { day: "2-digit", month: "short" });
    } catch {
      return dateStr;
    }
  };

  return (
    <section className="selectedDayBox">
      <div className="selectedDayHeader">
        <div className="selectedDayTitle">
          <CalendarDays size={13} style={{ color: "var(--accent)" }} />
          <strong>Dia {formatSelectedDateShort(selectedDate)}</strong>
        </div>
        <span className="selectedDayBadge">
          {selectedDayPosts.length === 1 ? "1 post" : `${selectedDayPosts.length} posts`}
        </span>
      </div>

      {selectedDayPosts.length > 0 ? (
        <div className="dayPostsTabs">
          {selectedDayPosts.map((post, idx) => {
            const meta = taskMetaMap.get(post.id) || {
              tag: post.isCollab ? "01 Collab" : `Arte ${String(idx + 1).padStart(2, "0")}`,
              autoTitle: post.title || post.profile || "Publicação",
              seqNumber: idx + 1,
              isCollab: Boolean(post.isCollab),
              profile: post.profile || "",
            };

            const getDisplayLabel = () => {
              if (post.title && !isAutoGeneratedTitle(post.title, post.profile)) {
                return post.profile ? `${post.profile} • ${post.title}` : post.title;
              }
              if (post.isCollab) {
                const p1 = post.profile || "";
                const p2 = post.collabProfile || "";
                return p1 && p2 ? `${p1} + ${p2}` : (p1 || p2 || "Collab");
              }
              return post.profile || "Publicação";
            };

            const label = getDisplayLabel();

            const isDropTarget = dragOverPostId === post.id;
            const dropPosClass = isDropTarget
              ? dragOverPosition === "after"
                ? "dropTargetAfter"
                : "dropTargetBefore"
              : "";

            return (
              <div
                key={post.id}
                role="button"
                tabIndex={0}
                draggable={true}
                onDragStart={(e) => onPostTabDragStart(e, post, label)}
                onDragEnd={onDragEnd}
                onDragOver={(e) => onPostTabDragOver(e, post.id)}
                onDragLeave={(e) => onPostTabDragLeave(e, post.id)}
                onDrop={(e) => onPostTabDrop(e, post)}
                className={`dayPostTab ${post.id === selectedId ? "active" : ""} ${dragSource?.postId === post.id ? "isDragSource" : ""} ${dropPosClass}`}
                onClick={() => onSelect(post)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" || e.key === " ") {
                    e.preventDefault();
                    onSelect(post);
                  }
                }}
                title={`${meta.tag}: ${label} • Arraste para reordenar ou mover para outro dia`}
              >
                <div className="dayPostTabMain">
                  <GripVertical size={12} className="dayPostDragHandle" />
                  <span className={`dayPostNum ${meta.isCollab ? "collabTag" : ""}`}>
                    {meta.tag}
                  </span>
                  <strong className="dayPostTitleText">{label}</strong>
                </div>

                <div className="dayPostTabEnd">
                  {post.isExtra && (
                    <span
                      style={{
                        fontSize: "10px",
                        fontWeight: 700,
                        padding: "1px 6px",
                        borderRadius: "4px",
                        background: "rgba(239, 93, 61, 0.12)",
                        color: "var(--accent, #ef5d3d)",
                        border: "1px solid rgba(239, 93, 61, 0.25)",
                        whiteSpace: "nowrap",
                      }}
                      title={`Arte Extra: ${post.extraFormat || "Avulsa"}`}
                    >
                      {post.extraFormat || "Extra"}
                    </span>
                  )}

                  {post.isCollab && (
                    <span className="dayPostCollabBadge" title="Publicação em Collab">
                      <Users size={10} />
                      <span>Collab</span>
                    </span>
                  )}

                  {selectedDayPosts.length > 1 && (
                    <div className="dayPostReorderButtons">
                      {idx > 0 && (
                        <button
                          type="button"
                          className="dayPostReorderBtn"
                          onClick={(e) => {
                            e.stopPropagation();
                            onReorderPosts?.(post.id, selectedDayPosts[idx - 1].id, "before");
                          }}
                          title="Mover para cima"
                        >
                          <ChevronUp size={11} />
                        </button>
                      )}
                      {idx < selectedDayPosts.length - 1 && (
                        <button
                          type="button"
                          className="dayPostReorderBtn"
                          onClick={(e) => {
                            e.stopPropagation();
                            onReorderPosts?.(post.id, selectedDayPosts[idx + 1].id, "after");
                          }}
                          title="Mover para baixo"
                        >
                          <ChevronDown size={11} />
                        </button>
                      )}
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      ) : (
        <div style={{ fontSize: "10px", color: "var(--muted)", padding: "2px 0" }}>
          Nenhuma publicação neste dia.
        </div>
      )}

      <button
        type="button"
        className="dayActionBtn"
        onClick={() => onCreate(selectedDate)}
      >
        <Plus size={11} /> {selectedDayPosts.length > 0 ? "Outro post neste dia" : "Criar post neste dia"}
      </button>
    </section>
  );
}
