"use client";
import {FormEvent,useEffect,useState} from "react";
import {Camera,CheckCircle2,FileUp,MapPin,MessageSquare,Play,Save,Trash2} from "lucide-react";
import {Button} from "../../components/ui/Button/Button";
import * as api from "../../lib/api/work-items-api";
import styles from "../WorkManagementScreen.module.css";

const externalNext:Record<string,string|undefined>={PLANNED:"READY",READY:"DEPARTED",DEPARTED:"IN_TRANSIT",IN_TRANSIT:"ARRIVED",ARRIVED:"IN_PROGRESS",IN_PROGRESS:"RETURNING",RETURNING:"FINISHED"};
export function WorkItemCapabilitiesPanel({item,onRefresh}:{item:any;onRefresh:()=>Promise<void>}){
  const[content,setContent]=useState<any>(null),[photo,setPhoto]=useState<any>(null),[external,setExternal]=useState<any>(null),[events,setEvents]=useState<any[]>([]),[assets,setAssets]=useState<any[]>([]),[comment,setComment]=useState(""),[checkTitle,setCheckTitle]=useState(""),[busy,setBusy]=useState(false);
  const load=async()=>{const results=await Promise.allSettled([api.getWorkItemEvents(item.id),item.type==="TASK"?api.getCapability(item.id,"content"):Promise.resolve(null),api.getCapability(item.id,"photo-job"),api.getCapability(item.id,"external-operation"),api.listWorkItemAssets(item.id)]);if(results[0].status==="fulfilled")setEvents(results[0].value);if(results[1].status==="fulfilled")setContent(results[1].value);if(results[2].status==="fulfilled")setPhoto(results[2].value);if(results[3].status==="fulfilled")setExternal(results[3].value);if(results[4].status==="fulfilled")setAssets(results[4].value)};
  useEffect(()=>{void load()},[item.id]);
  const run=async(action:()=>Promise<unknown>)=>{setBusy(true);try{await action();await onRefresh();await load()}finally{setBusy(false)}};
  const submitData=(event:FormEvent<HTMLFormElement>,capability:string)=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries());void run(()=>api.saveCapability(item.id,capability,data))};
  return <div className={styles.capabilities}>
    <section><h3>Checklist</h3><form className={styles.inlineForm} onSubmit={event=>{event.preventDefault();if(checkTitle.trim())void run(()=>api.addChecklistItem(item.id,{title:checkTitle.trim()})).then(()=>setCheckTitle(""))}}><input value={checkTitle} onChange={event=>setCheckTitle(event.target.value)} placeholder="Nova microação"/><Button size="small">Adicionar</Button></form>{item.checklist?.map((entry:any)=><label className={styles.check} key={entry.id}><input type="checkbox" checked={Boolean(entry.completed_at)} onChange={event=>void run(()=>api.toggleChecklistItem(item.id,entry.id,event.target.checked))}/><span>{entry.title}</span></label>)}</section>
    {item.type==="TASK"&&<section><h3>Conteúdo editorial</h3><form className={styles.stackForm} onSubmit={event=>submitData(event,"content")}><input name="head" defaultValue={content?.head||""} placeholder="Head"/><textarea name="caption" defaultValue={content?.caption||""} placeholder="Legenda"/><div className={styles.formGrid}><select name="channel" defaultValue={content?.channel||"INSTAGRAM"}><option>INSTAGRAM</option><option>FACEBOOK</option><option>TIKTOK</option><option>LINKEDIN</option><option>YOUTUBE</option></select><select name="format" defaultValue={content?.format||"FEED"}><option>FEED</option><option>STORY</option><option>FEED_STORY</option><option>REEL</option><option>CAROUSEL</option><option>VIDEO</option><option>SHORT</option></select></div><Button type="submit" size="small" icon={<Save/>} loading={busy}>Salvar conteúdo</Button></form></section>}
    <section><h3><FileUp/> Arquivos</h3><label className={styles.upload}><FileUp/><span>{busy?"Enviando...":"Adicionar arquivo"}</span><input type="file" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void run(()=>api.uploadWorkItemAsset(item.id,file));event.currentTarget.value=""}}/></label><div className={styles.assetList}>{assets.map(asset=><div key={asset.id}><a href={asset.url} target="_blank" rel="noreferrer">{asset.originalName}</a><span>v{asset.versionNumber||1} · {Math.ceil(Number(asset.byteSize)/1024)} KB</span><button aria-label="Excluir arquivo" onClick={()=>void run(()=>api.deleteWorkItemAsset(item.id,asset.id))}><Trash2/></button></div>)}</div></section>
    <section><h3><Camera/> Lote fotográfico</h3><form className={styles.metricForm} onSubmit={event=>{event.preventDefault();const values=Object.fromEntries([...new FormData(event.currentTarget)].map(([key,value])=>[key,Number(value)]));void run(()=>api.saveCapability(item.id,"photo-job",values))}}>{[["capturedCount","Captadas","captured_count"],["selectedCount","Selecionadas","selected_count"],["targetEditCount","A editar","target_edit_count"],["editedCount","Editadas","edited_count"],["exportedCount","Exportadas","exported_count"],["deliveredCount","Entregues","delivered_count"]].map(([name,label,key])=><label key={name}><span>{label}</span><input name={name} type="number" min="0" defaultValue={photo?.[key]||0}/></label>)}<Button type="submit" size="small">Atualizar lote</Button></form></section>
    <section><h3><MapPin/> Operação externa</h3>{!external?<form className={styles.stackForm} onSubmit={event=>submitData(event,"external-operation")}><input name="title" defaultValue={item.title}/><select name="operationType"><option>CAPTURE</option><option>MEETING</option><option>CLIENT_VISIT</option><option>EVENT_COVERAGE</option><option>DELIVERY</option><option>PICKUP</option><option>OTHER</option></select><input name="locationName" placeholder="Local"/><textarea name="briefing" placeholder="Briefing"/><Button type="submit" size="small">Preparar externa</Button></form>:<div className={styles.externalMode}><b>{external.status}</b><span>{external.location_name||"Local não informado"}</span>{externalNext[external.status]&&<Button icon={<Play/>} loading={busy} onClick={()=>void run(()=>api.transitionExternalOperation(item.id,externalNext[external.status]!))}>Avançar para {externalNext[external.status]}</Button>}<Button variant="glass" icon={<MapPin/>} onClick={()=>navigator.geolocation.getCurrentPosition(position=>void run(()=>api.addExternalLocation(item.id,{latitude:position.coords.latitude,longitude:position.coords.longitude,accuracyMeters:position.coords.accuracy,capturedAt:new Date().toISOString()})))}>Registrar localização</Button></div>}</section>
    <section><h3><MessageSquare/> Comentários</h3><form className={styles.inlineForm} onSubmit={event=>{event.preventDefault();if(comment.trim())void run(()=>api.addComment(item.id,comment.trim())).then(()=>setComment(""))}}><input value={comment} onChange={event=>setComment(event.target.value)} placeholder="Escrever comentário"/><Button size="small">Enviar</Button></form></section>
    <section><h3><CheckCircle2/> Histórico</h3><div className={styles.timeline}>{events.slice(0,20).map(event=><div key={event.id}><b>{event.event_type}</b><span>{event.actor_name||"Sistema"} · {new Date(event.created_at).toLocaleString("pt-BR")}</span></div>)}</div></section>
  </div>;
}
